Repository rlworkgroup/garage, pull requests merged in 2018-06, with the labels that each got.

#83 Check docstrings only on added files
  scripts/travisci/check_flake8.sh
  scripts/travisci/check_pylint.sh
Labels: quality

#81 All policies now check for gym.spaces.Box
  garage/envs/grid_world_env.py
  garage/envs/normalized_env.py
  garage/envs/occlusion_env.py
  garage/exploration_strategies/ou_strategy.py
  garage/policies/categorical_conv_policy.py
  garage/policies/categorical_gru_policy.py
  garage/policies/categorical_mlp_policy.py
  garage/tf/envs/base.py
  garage/tf/policies/gaussian_mlp_policy.py
  tests/algos/test_trpo.py
Labels: bug

#78 Fixed PointEnv for test_envs
  garage/envs/mujoco/point_env.py
Labels: bug

#76 Add mujoco sawyer envs
  garage/envs/mujoco/sawyer/__init__.py
  garage/envs/mujoco/sawyer/bin_sorting_env.py
  garage/envs/mujoco/sawyer/block_stacking_env.py
  garage/envs/mujoco/sawyer/pick_and_place_env.py
  tests/envs/test_sawyer_envs.py
  vendor/mujoco_models/bin_sorting.xml
  vendor/mujoco_models/block_stacking.xml
  vendor/mujoco_models/blue_bin.xml
  vendor/mujoco_models/green_bin.xml
  vendor/mujoco_models/meshes/base.STL
  vendor/mujoco_models/meshes/electric_gripper_base.STL
  vendor/mujoco_models/meshes/extended_narrow.STL
  vendor/mujoco_models/meshes/extended_wide.STL
  vendor/mujoco_models/meshes/half_round_tip.STL
  vendor/mujoco_models/meshes/head.STL
  vendor/mujoco_models/meshes/l0.STL
  vendor/mujoco_models/meshes/l1.STL
  vendor/mujoco_models/meshes/l2.STL
  vendor/mujoco_models/meshes/l3.STL
  vendor/mujoco_models/meshes/l4.STL
  vendor/mujoco_models/meshes/l5.STL
  vendor/mujoco_models/meshes/l6.STL
  vendor/mujoco_models/meshes/paddle_tip.STL
  vendor/mujoco_models/meshes/pedestal.STL
  vendor/mujoco_models/pick_and_place.xml
  vendor/mujoco_models/red_bin.xml
  vendor/mujoco_models/sawyer_robot.xml
  vendor/mujoco_models/shared.xml
  vendor/mujoco_models/shared_assets.xml
Labels: robots

#90 Renamed run_experiment_lite to run_experiment
  contrib/bichengcao/examples/trpo_gym_Acrobot-v1.py
  contrib/bichengcao/examples/trpo_gym_CartPole-v0.py
  contrib/bichengcao/examples/trpo_gym_CartPole-v1.py
  contrib/bichengcao/examples/trpo_gym_MountainCar-v0.py
  contrib/bichengcao/examples/trpo_gym_Pendulum-v0.py
  contrib/rllab_hyperopt/core.py
  contrib/rllab_hyperopt/example/main.py
  contrib/ros/envs/sawyer/launchers/trpo_real_sawyer_pnp.py
  contrib/ros/envs/sawyer/launchers/trpo_real_sawyer_push.py
  contrib/ros/envs/sawyer/launchers/trpo_sim_sawyer_pnp.py
  contrib/ros/envs/sawyer/launchers/trpo_sim_sawyer_push.py
  docs/user/experiments.rst
  examples/cluster_demo.py
  examples/cluster_gym_mujoco_demo.py
  examples/ddpg_cartpole.py
  examples/trpo_cartpole_pickled.py
  examples/trpo_cartpole_recurrent.py
  examples/trpo_gym_cartpole.py
  examples/trpo_gym_pendulum.py
  examples/trpo_gym_tf_cartpole.py
  garage/misc/instrument.py
  garage/tf/launchers/trpo_cartpole.py
  garage/tf/launchers/trpo_cartpole_recurrent.py
  garage/tf/launchers/vpg_cartpole.py
  scripts/resume_training.py
  scripts/run_experiment.py
  tests/envs/test_sawyer_envs.py
Labels: housecleaning

#89 Remove quotes in filename variables in pep8 checks
  scripts/travisci/check_flake8.sh
  scripts/travisci/check_pylint.sh
Labels: quality
