Repository rlworkgroup/garage, pull requests merged in 2019-02, with the labels that each got.

#471 Add tf/REPS
  examples/tf/reps_gym_cartpole.py
  garage/tf/algos/__init__.py
  garage/tf/algos/reps.py
  garage/tf/regressors/gaussian_conv_regressor.py
  tests/garage/tf/algos/test_reps.py
Labels: algos, tf

#544 Exit with a non-zero status in check_tests script
  scripts/travisci/check_cronjob_tests.sh
  scripts/travisci/check_tests.sh
Labels: bug

#552 Exit with a non-zero status in check_tests script
  scripts/travisci/check_cronjob_tests.sh
  scripts/travisci/check_tests.sh
Labels: bug

#551 Update CHANGELOG for the 2018.10.1 release
  CHANGELOG.md
Labels: packaging
