Repository rlworkgroup/garage, pull requests merged in 2019-12, with the labels that each got.

#1085 Adjust pytest options
  Makefile
  setup.cfg
Labels: ready-to-merge

#1083 Make matplotlib a dev dependency
  docs/requirements.txt
  setup.py
  src/garage/np/exploration_strategies/ou_strategy.py
Labels: ready-to-merge

#1069 Set TotalEnvSteps as the default Tensorboard x-axis
  setup.py
  src/garage/experiment/experiment_wrapper.py
Labels: ready-to-merge

#1079 Add tests for long running examples
  Makefile
  examples/tf/dqn_pong.py
  examples/tf/ppo_memorize_digits.py
  examples/tf/trpo_cubecrash.py
  tests/integration_tests/test_examples.py
Labels: needs backport, ready-to-merge

#1093 Refactor n_epoch_cycles
  examples/np/cem_cartpole.py
  examples/np/cma_es_cartpole.py
  examples/tf/ddpg_pendulum.py
  examples/tf/dqn_cartpole.py
  examples/tf/dqn_pong.py
  examples/tf/her_ddpg_fetchreach.py
  examples/tf/td3_pendulum.py
  examples/torch/ddpg_pendulum.py
  src/garage/experiment/local_runner.py
  src/garage/np/algos/cem.py
  src/garage/np/algos/off_policy_rl_algorithm.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  tests/benchmarks/garage/tf/algos/test_benchmark_ddpg.py
  tests/benchmarks/garage/tf/algos/test_benchmark_her.py
  tests/benchmarks/garage/tf/algos/test_benchmark_td3.py
  tests/benchmarks/garage/tf/policies/test_benchmark_continuous_mlp_policy.py
  tests/benchmarks/garage/tf/q_functions/test_benchmark_continuous_mlp_q_function.py
  tests/garage/experiment/test_resume.py
  tests/garage/np/algos/test_cem.py
  tests/garage/np/algos/test_cma_es.py
  tests/garage/tf/algos/test_ddpg.py
  tests/garage/tf/algos/test_dqn.py
  tests/garage/tf/algos/test_td3.py
  tests/garage/torch/algos/test_ddpg.py
Labels: needs force push

#1006 Eliminate unnecessary worker startup
  examples/tf/dqn_pong.py
  src/garage/experiment/experiment_wrapper.py
  src/garage/experiment/local_runner.py
  src/garage/sampler/base.py
  src/garage/sampler/batch_sampler.py
  src/garage/sampler/is_sampler.py
  src/garage/sampler/ray_sampler.py
  src/garage/tf/experiment/local_tf_runner.py
  src/garage/tf/samplers/batch_sampler.py
  tests/garage/sampler/test_is_sampler.py
  tests/garage/sampler/test_sampler.py
  tests/garage/tf/algos/test_trpo.py
  tests/garage/tf/samplers/test_tf_batch_sampler.py
Labels: needs force push

#1103 Add a special Docker build stage to nightlies
  .travis.yml
Labels: ready-to-merge

#1098 Update gym to 0.15.4
  setup.py
  src/garage/envs/base.py
  tests/garage/envs/test_garage_env.py
Labels: ready-to-merge

#881 Propose new Sampler API and port Ray Sampler
  .pylintrc
  src/garage/sampler/__init__.py
  src/garage/sampler/batch_sampler.py
  src/garage/sampler/ray_sampler.py
  src/garage/sampler/sampler.py
  src/garage/sampler/utils.py
  src/garage/sampler/worker.py
  src/garage/sampler/worker_factory.py
  src/garage/tf/samplers/batch_sampler.py
  src/garage/tf/samplers/ray_sampler.py
  tests/garage/sampler/test_ray_batched_sampler.py
  tests/garage/tf/samplers/test_ray_batched_sampler_tf.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1108 Add HalfCheetah meta envs
  src/garage/envs/half_cheetah_dir_env.py
  src/garage/envs/half_cheetah_env_meta_base.py
  src/garage/envs/half_cheetah_vel_env.py
  tests/garage/envs/test_half_cheetah_meta_envs.py
Labels: ready-to-merge
