Repository rlworkgroup/garage, pull requests merged in 2019-01, with the labels that each got.

#450 Updates to RandomizedEnv unit tests
  garage/envs/mujoco/randomization/variation.py
  tests/garage/envs/mujoco/randomization/test_dynamics_rand.py
Labels: tests

#463 Fix pre_commit version to avoid exception errors
  environment.yml
Labels: bug

#484 Remove unnecessary MJKEY check in Docker Makefile
  Makefile
Labels: housecleaning
