Repository rlworkgroup/garage, pull requests merged in 2019-11, with the labels that each got.

#977 Add tests for tf/ConjugateGradientOptimizer
  src/garage/misc/krylov.py
  src/garage/tf/optimizers/conjugate_gradient_optimizer.py
  src/garage/tf/regressors/bernoulli_mlp_regressor.py
  src/garage/tf/regressors/categorical_mlp_regressor.py
  tests/garage/tf/optimizers/test_conjugate_gradient_optimizer.py
Labels: ready-to-merge

#982 Remove Serializable
  .pylintrc
  src/garage/core/__init__.py
  src/garage/core/serializable.py
  src/garage/envs/base.py
  src/garage/envs/dm_control/dm_control_env.py
  src/garage/envs/env_spec.py
  src/garage/envs/grid_world_env.py
  src/garage/envs/normalized_env.py
  src/garage/envs/point_env.py
  src/garage/experiment/experiment.py
  src/garage/np/algos/nop.py
  src/garage/np/exploration_strategies/gaussian_strategy.py
  src/garage/np/q_functions/base.py
  src/garage/np/regressors/product_regressor.py
  src/garage/tf/optimizers/first_order_optimizer.py
  src/garage/tf/optimizers/lbfgs_optimizer.py
  src/garage/tf/optimizers/penalty_lbfgs_optimizer.py
  src/garage/tf/policies/uniform_control_policy.py
  tests/fixtures/policies/dummy_policy.py
  tests/fixtures/policies/dummy_recurrent_policy.py
Labels: needs force push

#961 Add missing unit test to tf/DDPG
  src/garage/tf/algos/ddpg.py
  src/garage/tf/policies/continuous_mlp_policy.py
  tests/garage/tf/algos/test_ddpg.py
  tests/garage/tf/policies/test_continuous_mlp_policy.py
Labels: ready-to-merge

#988 Remove garage.misc.console
  examples/sim_policy.py
  src/garage/experiment/experiment.py
  src/garage/experiment/experiment_wrapper.py
  src/garage/misc/console.py
  tests/garage/experiment/test_experiment.py
  tests/integration_tests/test_sigint.py
Labels: needs force push

#990 Remove layers lib based example
  examples/tf/trpo_cartpole_recurrent.py
  examples/tf/trpo_cartpole_recurrent_with_model.py
Labels: ready-to-merge

#989 Remove model-specific algorithm tests
  tests/garage/tf/algos/test_ppo.py
  tests/garage/tf/algos/test_ppo_with_model.py
  tests/garage/tf/algos/test_ppo_with_model_baseline.py
  tests/garage/tf/algos/test_ppo_with_models.py
  tests/garage/tf/algos/test_trpo.py
  tests/garage/tf/algos/test_trpo_with_model.py
Labels: ready-to-merge

#992 Update README.md
  README.md
Labels: ready-to-merge

#1000 Fix release VERSION
  VERSION
Labels: ready-to-merge

#1002 Backport #802 for auto API docs generation
  .gitignore
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  docs/user/experiments.rst
  readthedocs.yml
  setup.py
Labels: ready-to-merge

#995 Update citation instructions in the docs
  docs/index.rst
Labels: ready-to-merge

#999 Fix typos in CHANGELOG, bump VERSION
  CHANGELOG.md
  VERSION
Labels: ready-to-merge

#1008 Fix release branch regex
  .travis.yml
Labels: ready-to-merge

#1011 Add torch/PPO to README.md
  README.md
Labels: ready-to-merge

#1010 Add MT-TRPO example
  examples/tf/multi_env_trpo.py
Labels: ready-to-merge

#996 Add benchmark script for ContinuousMLPBaseline
  tests/benchmarks/garage/tf/baselines/test_benchmark_continuous_mlp_baseline.py
Labels: ready-to-merge

#1014 Move docs build to pre-commit job
  .travis.yml
  Makefile
Labels: ready-to-merge

#1013 Add flake8 exception for torch.nn.functional as F
  setup.cfg
Labels: ready-to-merge

#1009 Fix examples in tf branch
  src/garage/envs/base.py
  src/garage/misc/tensor_utils.py
  src/garage/sampler/off_policy_vectorized_sampler.py
  src/garage/sampler/on_policy_vectorized_sampler.py
  src/garage/sampler/ray_sampler.py
  src/garage/sampler/utils.py
  src/garage/tf/q_functions/continuous_mlp_q_function.py
  tests/garage/misc/test_tensor_utils.py
  tests/garage/sampler/test_utils.py
Labels: ready-to-merge

#1022 Fix ConjugateGradientOptimizer test
  tests/garage/tf/optimizers/test_conjugate_gradient_optimizer.py
Labels: ready-to-merge

#1017 Add stats of total env steps
  .pylintrc
  scripts/garage
  src/garage/experiment/local_runner.py
  src/garage/experiment/snapshotter.py
  src/garage/np/algos/batch_polopt.py
  src/garage/np/algos/off_policy_rl_algorithm.py
  src/garage/sampler/off_policy_vectorized_sampler.py
  src/garage/sampler/on_policy_vectorized_sampler.py
  src/garage/tf/algos/batch_polopt.py
  tests/benchmarks/garage/tf/algos/test_benchmark_trpo.py
  tests/fixtures/tf/algos/dummy_off_policy_algo.py
  tests/garage/experiment/test_resume.py
  tests/garage/experiment/test_snapshotter_integration.py
  tests/garage/sampler/test_is_sampler.py
  tests/garage/sampler/test_on_policy_vectorized_sampler.py
  tests/garage/sampler/test_sampler.py
  tests/garage/tf/experiment/test_local_tf_runner.py
Labels: benchmarks, ready-to-merge

#1031 Fix torch packaging and use package in the CI
  Makefile
  docker/Dockerfile.base.16.04
  docker/Dockerfile.base.18.04
  docker/Dockerfile.runtime
  environment.yml
  src/garage/torch/__init__.py
Labels: needs backport, ready-to-merge

#928 Support non-linearity function and module for PyTorch Module
  src/garage/torch/modules/mlp_module.py
  src/garage/torch/modules/multi_headed_mlp_module.py
  tests/garage/torch/modules/test_mlp_module.py
  tests/garage/torch/modules/test_multi_headed_mlp_module.py
Labels: needs backport, ready-to-merge

#1043 Install script changes for macOS 10.15.1
  scripts/setup_macos.sh
Labels: macos, needs backport, ready-to-merge

#1053 Improvements for PyTorch TRPO
  src/garage/torch/optimizers/conjugate_gradient_optimizer.py
Labels: ready-to-merge

#1029 Fix pickling in GarageEnv
  src/garage/envs/base.py
  tests/garage/tf/envs/test_base.py
Labels: needs backport, ready-to-merge

#1030 Remove optimizer_args from torch algos
  examples/torch/ddpg_pendulum.py
  examples/torch/ppo_pendulum.py
  examples/torch/vpg_pendulum.py
  src/garage/torch/algos/__init__.py
  src/garage/torch/algos/_utils.py
  src/garage/torch/algos/ddpg.py
  src/garage/torch/algos/ppo.py
  src/garage/torch/algos/trpo.py
  src/garage/torch/algos/vpg.py
  src/garage/torch/utils.py
  tests/benchmarks/garage/tf/algos/test_benchmark_ppo.py
  tests/benchmarks/garage/tf/algos/test_benchmark_trpo.py
  tests/benchmarks/garage/tf/algos/test_benchmark_vpg.py
  tests/garage/torch/algos/test_ddpg.py
  tests/garage/torch/algos/test_ppo.py
  tests/garage/torch/algos/test_torch_algo_utils.py
  tests/garage/torch/algos/test_trpo.py
  tests/garage/torch/algos/test_vpg.py
Labels: ready-to-merge

#1064 Update documentation to use "conda activate" (#1056)
  docs/user/installation.rst
Labels: needs backport, ready-to-merge

#1063 Make PyTorch experiments deterministic
  src/garage/experiment/deterministic.py
  tests/garage/experiment/test_deterministic.py
  tests/garage/torch/algos/test_ppo.py
Labels: needs backport, ready-to-merge

#1065 Add instructions for documenting tensor shapes
  CONTRIBUTING.md
Labels: ready-to-merge

#1060 Fix her_ddpg_fetchreach
  src/garage/replay_buffer/her_replay_buffer.py
  src/garage/tf/policies/continuous_mlp_policy.py
  tests/fixtures/envs/dummy/dummy_dict_env.py
  tests/garage/replay_buffer/__init__.py
  tests/garage/replay_buffer/test_her_replay_buffer.py
  tests/garage/replay_buffer/test_replay_buffer.py
  tests/garage/tf/policies/test_continuous_mlp_policy.py
Labels: needs backport

#1072 Rename xrange to range in docs (#1055)
  docs/user/implement_algo_advanced.rst
  docs/user/implement_algo_basic.rst
Labels: needs backport

#1058 Add TrajectoryBatch data type
  docs/_static/theme_overrides.css
  docs/conf.py
  setup.cfg
  src/garage/__init__.py
  src/garage/_dtypes.py
  tests/garage/.pylintrc
  tests/garage/test_dtypes.py
Labels: ready-to-merge

#987 Wrap examples in tests to run on CI
  Makefile
  examples/step_dm_control_env.py
  examples/step_env.py
  examples/tf/multi_env_ppo.py
  examples/tf/multi_env_trpo.py
  examples/tf/td3_pendulum.py
  examples/tf/trpo_swimmer_ray_sampler.py
  examples/tf/trpois_inverted_pendulum.py
  examples/tf/vpgis_inverted_pendulum.py
  examples/torch/ddpg_pendulum.py
  examples/torch/ppo_pendulum.py
  examples/torch/trpo_pendulum.py
  examples/torch/vpg_pendulum.py
  setup.py
  src/garage/experiment/experiment.py
  src/garage/experiment/local_runner.py
  tests/integration_tests/test_examples.py
Labels: needs backport, needs force push
