Repository rlworkgroup/garage, pull requests merged in 2019-03, with the labels that each got.

#550 Update CHANGELOG for the 2019.02.0 release
  CHANGELOG.md
Labels: packaging

#561 Use the right env variable for .bash_rc
  scripts/setup_linux.sh
Labels: bug

#560 Use the right env variable for .bash_rc
  scripts/setup_linux.sh
Labels: bug

#579 Add miscellaneous changes for benchmarking
  examples/tf/ppo_pendulum.py
  garage/baselines/linear_feature_baseline.py
  garage/tf/algos/npo.py
  garage/tf/baselines/deterministic_mlp_baseline.py
  garage/tf/baselines/gaussian_conv_baseline.py
  garage/tf/baselines/gaussian_mlp_baseline.py
  garage/tf/regressors/bernoulli_mlp_regressor.py
  garage/tf/regressors/categorical_mlp_regressor.py
  garage/tf/regressors/gaussian_conv_regressor.py
  garage/tf/regressors/gaussian_mlp_regressor.py
  garage/tf/samplers/batch_sampler.py
  tests/benchmarks/test_benchmark_ddpg.py
  tests/benchmarks/test_benchmark_her.py
  tests/benchmarks/test_benchmark_ppo.py
  tests/benchmarks/test_benchmark_trpo.py
  tests/wrappers.py
Labels: benchmarks

#595 Remove config_personal_template.py from setups
  scripts/setup_linux.sh
  scripts/setup_macos.sh
Labels: bug
