Repository rlworkgroup/garage, pull requests merged in 2020-07, with the labels that each got.

#1606 Add TensorBoard logging doc
  docs/index.md
  docs/user/monitor_experiments_with_tensorboard.md
Labels: documentation, ready-to-merge

#1664 Refactor GaussianCNNBaseline to inherit from GaussianCNNRegressorModel
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_cnn_baseline.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_cnn_policy.py
  examples/tf/ppo_memorize_digits.py
  examples/tf/trpo_cubecrash.py
  src/garage/np/baselines/baseline.py
  src/garage/np/baselines/linear_feature_baseline.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/baselines/continuous_mlp_baseline.py
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/regressors/__init__.py
  src/garage/tf/regressors/gaussian_cnn_regressor.py
  src/garage/tf/regressors/gaussian_cnn_regressor_model.py
  tests/garage/tf/algos/test_trpo.py
  tests/garage/tf/baselines/test_gaussian_cnn_baseline.py
  tests/garage/tf/regressors/test_gaussian_cnn_regressor.py
Labels: ready-to-merge

#1682 Remove "Subpackages" heading from API Reference
  docs/autoapi_templates/python/module.rst
Labels: documentation, ready-to-merge

#1688 Specify cloudpickle version for compatibility
  setup.py
Labels: ready-to-merge

#1615 Documentation on save, load, and resume experiments
  .gitignore
  docs/index.md
  docs/user/save_load_resume_exp.md
  examples/tf/trpo_gym_tf_cartpole_pretrained.py
Labels: documentation, ready-to-merge

#1691 Add behavioral cloning to README.md
  README.md
Labels: ready-to-merge

#1680 Remove docs build from pre-commit job
  Makefile
Labels: ready-to-merge

#1689 Create DATA_PATH dir for docker if not exists
  Makefile
Labels: ready-to-merge

#1686 Refactor ContinuousMLPBaseline
  benchmarks/src/garage_benchmarks/experiments/baselines/continuous_mlp_baseline.py
  src/garage/tf/baselines/continuous_mlp_baseline.py
  src/garage/tf/regressors/__init__.py
  src/garage/tf/regressors/continuous_mlp_regressor.py
  tests/garage/tf/algos/test_ppo.py
  tests/garage/tf/baselines/test_continuous_mlp_baseline.py
  tests/garage/tf/regressors/test_continuous_mlp_regressor.py
Labels: ready-to-merge

#1693 Add garage.sampler to API Reference
  docs/index.md
Labels: ready-to-merge

#1683 Retry during coverage upload
  Makefile
Labels: backport-to-2020.06, ready-to-merge

#1696 Open browser when docs are done building
  Makefile
  docs/Makefile
Labels: ready-to-merge

#1690 Update docker documentation
  docs/index.md
  docs/user/docker.md
Labels: ready-to-merge

#1695 Make docs headings more consistent
  docs/user/experiments.rst
  docs/user/implement_algo.rst
  docs/user/implement_env.rst
  docs/user/monitor_experiments_with_tensorboard.md
  docs/user/pixel_observations.md
  docs/user/save_load_resume_exp.md
  docs/user/training_a_policy.md
  docs/user/writing_documentation.md
Labels: ready-to-merge

#1697 Skip commit message check for backports
  scripts/check_commit_message
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1703 Update pre-commit hook revisions
  .pre-commit-config.yaml
Labels: ready-to-merge

#1684 GarageEnv wraps BulletEnv
  src/garage/envs/bullet/__init__.py
  src/garage/envs/bullet/bullet_env.py
  src/garage/envs/garage_env.py
  tests/garage/envs/bullet/test_bullet_env.py
  tests/garage/envs/test_garage_env.py
  tests/garage/tf/envs/test_base.py
Labels: envs, ready-to-merge

#1708 Update version for v2020.09.0rc2
  VERSION
Labels: ready-to-merge

#1710 Set low max episode step in test
  tests/garage/envs/bullet/test_bullet_env.py
Labels: ready-to-merge

#1617 Fix a typo to allow evaluating algos deterministically
  src/garage/sampler/utils.py
  tests/fixtures/policies/dummy_policy.py
  tests/garage/sampler/test_utils.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1711 Add build hooks for DockerHub
  docker/hooks/build
Labels: backport-to-2020.06, ready-to-merge

#1707 Add isort to pre-commit
  .pre-commit-config.yaml
  .pylintrc
  setup.cfg
  setup.py
  src/garage/envs/dm_control/__init__.py
  src/garage/experiment/experiment.py
  src/garage/experiment/local_runner.py
  src/garage/tf/q_functions/__init__.py
  src/garage/torch/algos/__init__.py
  src/garage/torch/policies/__init__.py
  src/garage/torch/value_functions/__init__.py
  tests/garage/.pylintrc
  tests/garage/torch/algos/test_pearl.py
Labels: ready-to-merge

#1714 Backport #1617 to release-2020.06
  src/garage/sampler/utils.py
  tests/fixtures/policies/dummy_policy.py
  tests/garage/sampler/test_utils.py
Labels: ready-to-merge

#1692 Update code syntax in save, load, resume experiment
  docs/user/save_load_resume_exp.md
Labels: documentation, ready-to-merge

#1706 Update docker gpu support to use the --gpus option
  Makefile
Labels: ready-to-merge

#1720 Use a codecov upload token
  Makefile
Labels: ready-to-merge

#1719 Fail the build if codecov upload fails
  Makefile
Labels: ready-to-merge

#1721 Fix pipenv dependency resolution
  setup.py
Labels: backport-to-2020.06, ready-to-merge

#1705 Refactor GaussianMLPBaseline
  benchmarks/src/garage_benchmarks/experiments/algos/ppo_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_mlp_baseline.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_gru_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_lstm_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_mlp_policy.py
  examples/tf/ppo_pendulum.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/regressors/__init__.py
  src/garage/tf/regressors/gaussian_mlp_regressor.py
  tests/fixtures/policies/dummy_policy.py
  tests/garage/envs/bullet/test_bullet_env.py
  tests/garage/sampler/test_utils.py
  tests/garage/tf/algos/test_npo.py
  tests/garage/tf/algos/test_ppo.py
  tests/garage/tf/algos/test_trpo.py
  tests/garage/tf/baselines/test_gaussian_mlp_baseline.py
  tests/garage/tf/regressors/test_gaussian_mlp_regressor.py
Labels: ready-to-merge

#1726 Fix branch regex to prevent duplicate builds
  .travis.yml
Labels: ready-to-merge

#1725 Fix branch regex to prevent duplicate builds
  .travis.yml
Labels: ready-to-merge

#1702 Update docker documentation
  Makefile
  docs/user/docker.md
Labels: ready-to-merge

#1642 Documentation on loading a trained policy
  docs/index.md
  docs/user/reuse_garage_policy.md
Labels: documentation, ready-to-merge

#1730 Conditionally imports BulletEnv
  src/garage/envs/garage_env.py
Labels: ready-to-merge

#1731 Mark test_td3_pendulum as flaky
  tests/garage/tf/algos/test_td3.py
Labels: ready-to-merge

#1733 Make the README less retrospective about py35
  .mdlrc
  README.md
Labels: ready-to-merge

#1627 Documentation on setting up a development environment
  docs/user/installation.rst
  docs/user/setting_up_your_development_environment.md
Labels: documentation, ready-to-merge

#1737 Remove hardcoded bullet env list
  src/garage/envs/bullet/__init__.py
  tests/garage/envs/bullet/test_bullet_env.py
Labels: ready-to-merge

#1738 Add dev environment setup to TOC
  docs/index.md
Labels: ready-to-merge

#1727 Remove garage.tf.regressors
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  src/garage/tf/baselines/gaussian_cnn_baseline_model.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/baselines/gaussian_mlp_baseline_model.py
  src/garage/tf/regressors/__init__.py
  src/garage/tf/regressors/bernoulli_mlp_regressor.py
  src/garage/tf/regressors/categorical_mlp_regressor.py
  src/garage/tf/regressors/categorical_mlp_regressor_model.py
  src/garage/tf/regressors/regressor.py
  tests/fixtures/regressors/__init__.py
  tests/fixtures/regressors/simple_gaussian_cnn_regressor.py
  tests/fixtures/regressors/simple_gaussian_mlp_regressor.py
  tests/fixtures/regressors/simple_mlp_regressor.py
  tests/garage/tf/regressors/__init__.py
  tests/garage/tf/regressors/test_bernoulli_mlp_regressor.py
  tests/garage/tf/regressors/test_categorical_mlp_regressor.py
Labels: ready-to-merge

#1639 Create ensure_your_experiments_are_reproducible.md
  docs/index.md
  docs/user/ensure_your_experiments_are_reproducible.md
  src/garage/envs/point_env.py
Labels: documentation, ready-to-merge

#1734 Unpin PyTorch
  setup.py
Labels: ready-to-merge

#1728 Rename CompletionRate to TerminationRate
  docs/user/experiments.rst
  docs/user/save_load_resume_exp.md
  docs/user/training_a_policy.md
  examples/jupyter/custom_env.ipynb
  examples/jupyter/trpo_gym_tf_cartpole.ipynb
  src/garage/_functions.py
  src/garage/tf/algos/te_npo.py
  tests/garage/experiment/test_meta_evaluator.py
  tests/garage/test_functions.py
Labels: ready-to-merge

#1744 Relax DQN test last_avg_reg
  tests/garage/tf/algos/test_dqn.py
Labels: ready-to-merge

#1747 Update reuse_garage_policy.md
  docs/user/reuse_garage_policy.md
Labels: ready-to-merge

#1746 Fix codecov retry loop
  Makefile
Labels: backport-to-2020.06, ready-to-merge

#1748 Relax threshold for flake SAC test
  tests/garage/torch/algos/test_sac.py
Labels: backport-to-2020.06, ready-to-merge

#1753 Fix codecov retry loop again
  Makefile
Labels: backport-to-2020.06, ready-to-merge

#1745 Relax last_avg_ret to deflaky test_td3
  tests/garage/tf/algos/test_td3.py
Labels: ready-to-merge

#1752 Update implement a env doc
  docs/user/implement_env.rst
Labels: ready-to-merge

#1754 Relax test_trpo_gru_cartpole
  tests/garage/tf/algos/test_trpo.py
Labels: ready-to-merge

#1750 Replace tf.distributions with tfp
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  src/garage/tf/baselines/gaussian_cnn_baseline_model.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/baselines/gaussian_mlp_baseline_model.py
  src/garage/tf/distributions/__init__.py
  src/garage/tf/distributions/bernoulli.py
  src/garage/tf/distributions/categorical.py
  src/garage/tf/distributions/diagonal_gaussian.py
  src/garage/tf/distributions/distribution.py
  src/garage/tf/distributions/recurrent_categorical.py
  src/garage/tf/distributions/recurrent_diagonal_gaussian.py
  src/garage/tf/models/gaussian_cnn_model.py
  src/garage/tf/policies/task_embedding_policy.py
  tests/fixtures/distributions/__init__.py
  tests/fixtures/distributions/dummy_distribution.py
  tests/fixtures/models/__init__.py
  tests/fixtures/models/simple_gaussian_cnn_model.py
  tests/fixtures/models/simple_gaussian_gru_model.py
  tests/fixtures/models/simple_gaussian_lstm_model.py
  tests/fixtures/models/simple_gaussian_mlp_model.py
  tests/fixtures/models/simple_mlp_merge_model.py
  tests/fixtures/policies/dummy_policy.py
  tests/fixtures/policies/dummy_recurrent_policy.py
  tests/garage/sampler/test_utils.py
  tests/garage/tf/baselines/test_gaussian_cnn_baseline.py
  tests/garage/tf/distributions/test_diagonal_gaussian.py
  tests/garage/tf/embeddings/test_gaussian_mlp_encoder.py
  tests/garage/tf/policies/test_gaussian_mlp_task_embedding_policy.py
Labels: ready-to-merge

#1759 Pin tfp to resolve install problems
  setup.py
Labels: backport-to-2020.06, ready-to-merge

#1760 Update CHANGELOG to v2020.06.1
  CHANGELOG.md
Labels: backport-to-2020.06, ready-to-merge

#1739 improve parameters of example her_ddpg_fetchreach
  examples/tf/her_ddpg_fetchreach.py
Labels: ready-to-merge

#1764 improve parameters of example her_ddpg_fetchreach (bp #1739)
  examples/tf/her_ddpg_fetchreach.py
Labels: ready-to-merge

#1770 Export task samplers in garage.experiment
  src/garage/experiment/__init__.py
Labels: ready-to-merge

#1771 Export EnvUpdates in garage.sampler
  src/garage/sampler/__init__.py
Labels: ready-to-merge

#1772 Remove old off-policy logging code
  benchmarks/src/garage_benchmarks/experiments/algos/td3_garage_tf.py
  examples/tf/td3_pendulum.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  tests/garage/tf/algos/test_dqn.py
  tests/garage/tf/algos/test_td3.py
Labels: ready-to-merge

#1776 Fix setup script for linux
  scripts/setup_linux.sh
Labels: ready-to-merge

#1781 Change dev install link from .md to .html
  docs/user/installation.rst
Labels: ready-to-merge

#1778 Nvidia Docker Headless
  Makefile
  docs/user/docker.md
Labels: ready-to-merge

#1783 Check for min docker version in Makefile
  Makefile
Labels: ready-to-merge

#1777 Update docker docs
  docs/user/docker.md
Labels: ready-to-merge

#1784 Unpin dm_control
  setup.py
Labels: ready-to-merge

#1765 Documentation on BC algorithm
  docs/conf.py
  docs/index.md
  docs/requirements.txt
  docs/user/algo_bc.md
  docs/user/images/bc_meanLoss.png
  docs/user/images/bc_stdLoss.png
  docs/user/images/pytorch.png
  docs/user/images/tensorflow.png
  docs/user/references.bib
  setup.py
  src/garage/torch/algos/bc.py
Labels: ready-to-merge

#1789 Fix broken image for bc doc
  docs/user/algo_bc.md
Labels: ready-to-merge

#1769 Add doctest for ci and doctest sample files
  Makefile
  docs/Makefile
  docs/conf.py
  docs/user/experiments.rst
  docs/user/implement_algo.rst
  docs/user/implement_env.rst
  src/garage/misc/tensor_utils.py
Labels: ready-to-merge

#1757 Set seed for all ops in TF tree
  src/garage/experiment/deterministic.py
  src/garage/tf/algos/te_npo.py
  src/garage/tf/baselines/continuous_mlp_baseline.py
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  src/garage/tf/baselines/gaussian_cnn_baseline_model.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/baselines/gaussian_mlp_baseline_model.py
  src/garage/tf/embeddings/gaussian_mlp_encoder.py
  src/garage/tf/models/categorical_cnn_model.py
  src/garage/tf/models/categorical_gru_model.py
  src/garage/tf/models/categorical_lstm_model.py
  src/garage/tf/models/categorical_mlp_model.py
  src/garage/tf/models/cnn.py
  src/garage/tf/models/cnn_mlp_merge_model.py
  src/garage/tf/models/cnn_model.py
  src/garage/tf/models/cnn_model_max_pooling.py
  src/garage/tf/models/gaussian_cnn_model.py
  src/garage/tf/models/gaussian_gru_model.py
  src/garage/tf/models/gaussian_lstm_model.py
  src/garage/tf/models/gaussian_mlp_model.py
  src/garage/tf/models/gru_model.py
  src/garage/tf/models/lstm_model.py
  src/garage/tf/models/mlp.py
  src/garage/tf/models/mlp_dueling_model.py
  src/garage/tf/models/mlp_merge_model.py
  src/garage/tf/models/mlp_model.py
  src/garage/tf/models/normalized_input_mlp_model.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/tf/q_functions/continuous_cnn_q_function.py
  src/garage/tf/q_functions/continuous_mlp_q_function.py
  src/garage/tf/q_functions/discrete_cnn_q_function.py
  src/garage/tf/q_functions/discrete_mlp_q_function.py
  tests/garage/experiment/test_deterministic.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1762 Add doc for sampling
  docs/index.md
  docs/user/sampling.md
Labels: ready-to-merge

#1820 Pin TF and torch to workaound #1819 & #1823
  setup.py
  tests/garage/sampler/test_multiprocessing_sampler.py
Labels: ready-to-merge

#1626 Add FragmentWorker for Off-Policy RL
  src/garage/experiment/local_runner.py
  src/garage/experiment/local_tf_runner.py
  src/garage/np/exploration_policies/add_gaussian_noise.py
  src/garage/sampler/__init__.py
  src/garage/sampler/_dtypes.py
  src/garage/sampler/_functions.py
  src/garage/sampler/default_worker.py
  src/garage/sampler/fragment_worker.py
  src/garage/sampler/vec_worker.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  src/garage/torch/algos/sac.py
  tests/garage/sampler/test_fragment_worker.py
Labels: ready-to-merge

#1791 Fix qf_derived_policy variable_scope
  src/garage/tf/policies/discrete_qf_derived_policy.py
  tests/garage/tf/policies/test_qf_derived_policy.py
Labels: backport-to-2019.10, backport-to-2020.06

#1814 Add git workflow doc
  docs/index.md
  docs/user/git_workflow.md
Labels: documentation, ready-to-merge

#1807 Use cudnn7-runtime for run-nvidia
  Makefile
  docker/hooks/build
  docs/user/docker.md
Labels: backport-to-2020.06, ready-to-merge
