Repository rlworkgroup/garage, pull requests merged in 2020-05, with the labels that each got.

#1326 Add ContinuousCNNQFunction
  src/garage/tf/models/__init__.py
  src/garage/tf/models/cnn_mlp_merge_model.py
  src/garage/tf/q_functions/__init__.py
  src/garage/tf/q_functions/continuous_cnn_q_function.py
  tests/garage/tf/models/test_cnn_mlp_merge_model.py
  tests/garage/tf/q_functions/test_continuous_cnn_q_function.py
Labels: ready-to-merge

#1317 Add value function for torch
  examples/torch/maml_ppo_half_cheetah_dir.py
  examples/torch/maml_trpo_half_cheetah_dir.py
  examples/torch/maml_trpo_ml10.py
  examples/torch/maml_vpg_half_cheetah_dir.py
  examples/torch/ppo_pendulum.py
  examples/torch/trpo_pendulum.py
  examples/torch/trpo_pendulum_ray_sampler.py
  examples/torch/vpg_pendulum.py
  src/garage/torch/algos/maml.py
  src/garage/torch/algos/maml_ppo.py
  src/garage/torch/algos/maml_trpo.py
  src/garage/torch/algos/maml_vpg.py
  src/garage/torch/algos/ppo.py
  src/garage/torch/algos/trpo.py
  src/garage/torch/algos/vpg.py
  src/garage/torch/optimizers/__init__.py
  src/garage/torch/optimizers/optimizer_wrapper.py
  src/garage/torch/value_functions/__init__.py
  src/garage/torch/value_functions/base.py
  src/garage/torch/value_functions/gaussian_mlp_value_function.py
  tests/benchmarks/auto/auto_benchmark_ppo.py
  tests/benchmarks/auto/auto_benchmark_trpo.py
  tests/benchmarks/garage/tf/algos/benchmark_ppo.py
  tests/benchmarks/garage/tf/algos/benchmark_trpo.py
  tests/benchmarks/garage/tf/algos/benchmark_vpg.py
  tests/garage/experiment/test_local_runner.py
  tests/garage/torch/algos/test_maml.py
  tests/garage/torch/algos/test_maml_ppo.py
  tests/garage/torch/algos/test_maml_trpo.py
  tests/garage/torch/algos/test_maml_vpg.py
  tests/garage/torch/algos/test_ppo.py
  tests/garage/torch/algos/test_trpo.py
  tests/garage/torch/algos/test_vpg.py
Labels: ready-to-merge

#1369 Add DeprecationWarnings to old-style samplers
  src/garage/sampler/batch_sampler.py
  src/garage/sampler/off_policy_vectorized_sampler.py
  src/garage/sampler/on_policy_vectorized_sampler.py
  src/garage/sampler/parallel_vec_env_executor.py
  src/garage/sampler/vec_env_executor.py
Labels: ready-to-merge

#1370 Add DeprecationWarning to run_experiment
  src/garage/experiment/experiment.py
Labels: ready-to-merge

#1357 Fix categorical primitives distribution argument
  src/garage/tf/models/categorical_gru_model.py
  src/garage/tf/models/categorical_lstm_model.py
  src/garage/tf/models/categorical_mlp_model.py
  src/garage/tf/policies/categorical_cnn_policy2.py
  src/garage/tf/policies/categorical_gru_policy2.py
  src/garage/tf/policies/categorical_lstm_policy2.py
  src/garage/tf/policies/categorical_mlp_policy2.py
  tests/garage/tf/models/test_categorical_cnn_model.py
  tests/garage/tf/models/test_categorical_gru_model.py
  tests/garage/tf/models/test_categorical_lstm_model.py
  tests/garage/tf/models/test_categorical_mlp_model.py
  tests/garage/tf/policies/test_categorical_cnn_policy2.py
  tests/garage/tf/policies/test_categorical_gru_policy2.py
  tests/garage/tf/policies/test_categorical_lstm_policy2.py
  tests/garage/tf/policies/test_categorical_mlp_policy2.py
Labels: needs backport

#1374 Fix PEARL.adapt_policy
  src/garage/torch/algos/pearl.py
Labels: ready-to-merge

#1368 Separate benchmark experiments into files
  tests/benchmark_helper.py
  tests/benchmarks/auto/auto_benchmark_ddpg.py
  tests/benchmarks/auto/auto_benchmark_ppo.py
  tests/benchmarks/auto/auto_benchmark_td3.py
  tests/benchmarks/auto/auto_benchmark_trpo.py
  tests/benchmarks/auto/auto_benchmark_vpg.py
  tests/benchmarks/auto/benchmarks.py
  tests/benchmarks/auto/experiments/__init__.py
  tests/benchmarks/auto/experiments/ddpg_garage_tf.py
  tests/benchmarks/auto/experiments/ppo_garage_pytorch.py
  tests/benchmarks/auto/experiments/ppo_garage_tf.py
  tests/benchmarks/auto/experiments/td3_garage_tf.py
  tests/benchmarks/auto/experiments/trpo_garage_pytorch.py
  tests/benchmarks/auto/experiments/trpo_garage_tf.py
  tests/benchmarks/auto/experiments/vpg_garage_pytorch.py
  tests/benchmarks/auto/experiments/vpg_garage_tf.py
  tests/benchmarks/auto/helper.py
Labels: ready-to-merge

#1378 Revert "Downgrade sphinx version (#1284)"
  docs/requirements.txt
  setup.py
Labels: ready-to-merge

#1382 Unpin sphinx
  docs/requirements.txt
  setup.py
Labels: ready-to-merge

#1332 MTSAC and examples
  examples/torch/mtsac_metaworld_ML1_pick_place.py
  examples/torch/mtsac_metaworld_MT10.py
  examples/torch/mtsac_metaworld_MT50.py
  examples/torch/sac_half_cheetah_batch.py
  src/garage/_functions.py
  src/garage/envs/multi_env_wrapper.py
  src/garage/replay_buffer/base.py
  src/garage/replay_buffer/path_buffer.py
  src/garage/torch/algos/__init__.py
  src/garage/torch/algos/mtsac.py
  src/garage/torch/algos/sac.py
  tests/garage/envs/test_multi_env_wrapper.py
  tests/garage/replay_buffer/test_path_buffer.py
  tests/garage/torch/algos/test_mtsac.py
  tests/garage/torch/algos/test_sac.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1387 Add new algorithms to README.md
  README.md
Labels: ready-to-merge

#1373 Fix PEARL example default num tasks
  examples/torch/pearl_ml10.py
  examples/torch/pearl_ml45.py
Labels: ready-to-merge

#1385 Fix pickling after HalfCheetahEnvMetaBase.set_task
  src/garage/envs/mujoco/half_cheetah_dir_env.py
  src/garage/envs/mujoco/half_cheetah_env_meta_base.py
  src/garage/envs/mujoco/half_cheetah_vel_env.py
  tests/garage/envs/test_half_cheetah_meta_envs.py
Labels: ready-to-merge

#1383 Update dependencies for docs
  docs/conf.py
  docs/requirements.txt
  readthedocs.yml
Labels: ready-to-merge

#1380 New plotting decorator for benchmarking
  tests/benchmarks/auto/benchmarks.py
  tests/benchmarks/auto/helper.py
Labels: ready-to-merge

#1384 Add max_eval_path_length to off-policy algorithms
  src/garage/np/algos/off_policy_rl_algorithm.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  src/garage/torch/algos/sac.py
Labels: ready-to-merge

#1327 Add Meta-World example for PPO and TRPO
  examples/torch/maml_trpo_metaworld_ml1_push.py
  examples/torch/mtppo_metaworld_ml1_push.py
  examples/torch/mtppo_metaworld_mt10.py
  examples/torch/mtppo_metaworld_mt50.py
  examples/torch/mttrpo_metaworld_ml1_push.py
  examples/torch/mttrpo_metaworld_mt10.py
  examples/torch/mttrpo_metaworld_mt50.py
  src/garage/torch/algos/maml.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1371 Use cloudpickle in old-style samplers
  src/garage/experiment/experiment_wrapper.py
  src/garage/experiment/local_runner.py
  src/garage/sampler/off_policy_vectorized_sampler.py
  src/garage/sampler/on_policy_vectorized_sampler.py
  src/garage/sampler/parallel_sampler.py
  src/garage/sampler/parallel_vec_env_executor.py
Labels: ready-to-merge

#1389 Relax timeout limit on MAML ML10
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1394 Make runner._sampler optional
  src/garage/experiment/local_runner.py
  src/garage/tf/experiment/local_tf_runner.py
  tests/garage/experiment/test_local_runner.py
  tests/garage/experiment/test_resume.py
Labels: ready-to-merge

#1393 Make Metaworld-based example naming consistent
  examples/tf/ddpg_pendulum.py
  examples/tf/ppo_pendulum.py
  examples/tf/rl2_ppo_metaworld_ml10.py
  examples/tf/rl2_ppo_metaworld_ml10_meta_test.py
  examples/tf/rl2_ppo_metaworld_ml1_push.py
  examples/tf/rl2_ppo_metaworld_ml45.py
  examples/tf/trpo_swimmer_ray_sampler.py
  examples/torch/maml_ppo_half_cheetah_dir.py
  examples/torch/maml_trpo_half_cheetah_dir.py
  examples/torch/maml_trpo_metaworld_ml10.py
  examples/torch/maml_trpo_metaworld_ml1_push.py
  examples/torch/maml_trpo_metaworld_ml45.py
  examples/torch/maml_vpg_half_cheetah_dir.py
  examples/torch/mtppo_metaworld_ml1_push.py
  examples/torch/mtppo_metaworld_mt10.py
  examples/torch/mtppo_metaworld_mt50.py
  examples/torch/mtsac_metaworld_ml1_pick_place.py
  examples/torch/mtsac_metaworld_mt10.py
  examples/torch/mtsac_metaworld_mt50.py
  examples/torch/mttrpo_metaworld_ml1_push.py
  examples/torch/mttrpo_metaworld_mt10.py
  examples/torch/mttrpo_metaworld_mt50.py
  examples/torch/pearl_half_cheetah_vel.py
  examples/torch/pearl_metaworld_ml10.py
  examples/torch/pearl_metaworld_ml1_push.py
  examples/torch/pearl_metaworld_ml45.py
  examples/torch/ppo_pendulum.py
  examples/torch/sac_half_cheetah_batch.py
  examples/torch/trpo_pendulum_ray_sampler.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1395 Separate algorithm benchmarks from tests
  benchmarks/__init__.py
  benchmarks/benchmark_algos.py
  benchmarks/experiments/__init__.py
  benchmarks/experiments/algos/__init__.py
  benchmarks/experiments/algos/ddpg_garage_tf.py
  benchmarks/experiments/algos/her_garage_tf.py
  benchmarks/experiments/algos/ppo_garage_pytorch.py
  benchmarks/experiments/algos/ppo_garage_tf.py
  benchmarks/experiments/algos/td3_garage_tf.py
  benchmarks/experiments/algos/trpo_garage_pytorch.py
  benchmarks/experiments/algos/trpo_garage_tf.py
  benchmarks/experiments/algos/vpg_garage_pytorch.py
  benchmarks/experiments/algos/vpg_garage_tf.py
  benchmarks/helper.py
  tests/benchmarks/auto/__init__.py
  tests/benchmarks/auto/benchmarks.py
  tests/benchmarks/auto/experiments/__init__.py
  tests/benchmarks/garage/tf/algos/__init__.py
  tests/benchmarks/garage/tf/algos/benchmark_ddpg.py
  tests/benchmarks/garage/tf/algos/benchmark_her.py
  tests/benchmarks/garage/tf/algos/benchmark_ppo.py
  tests/benchmarks/garage/tf/algos/benchmark_td3.py
  tests/benchmarks/garage/tf/algos/benchmark_trpo.py
  tests/benchmarks/garage/tf/algos/benchmark_vpg.py
Labels: ready-to-merge

#1405 Disable pytest-xdist in the CI
  setup.cfg
Labels: ready-to-merge

#1402 Remove pytest benchmark mark
  Makefile
  setup.cfg
Labels: ready-to-merge

#1400 Refactor baseline benchmarks
  benchmarks/benchmark_algos.py
  benchmarks/benchmark_baselines.py
  benchmarks/experiments/baselines/__init__.py
  benchmarks/experiments/baselines/continuous_mlp_baseline_tf.py
  benchmarks/experiments/baselines/gaussian_cnn_baseline_tf.py
  benchmarks/experiments/baselines/gaussian_mlp_baseline_tf.py
  benchmarks/helper.py
  benchmarks/parameters.py
  tests/benchmarks/garage/tf/baselines/__init__.py
  tests/benchmarks/garage/tf/baselines/benchmark_continuous_mlp_baseline.py
  tests/benchmarks/garage/tf/baselines/benchmark_gaussian_cnn_baseline.py
  tests/benchmarks/garage/tf/baselines/benchmark_gaussian_mlp_baseline.py
Labels: ready-to-merge

#1411 Create garage_benchmarks package
  benchmarks/experiments/algos/__init__.py
  benchmarks/experiments/baselines/__init__.py
  benchmarks/garage_benchmarks/__init__.py
  benchmarks/garage_benchmarks/benchmark_algos.py
  benchmarks/garage_benchmarks/benchmark_baselines.py
  benchmarks/garage_benchmarks/experiments/__init__.py
  benchmarks/garage_benchmarks/experiments/algos/__init__.py
  benchmarks/garage_benchmarks/experiments/algos/ddpg_garage_tf.py
  benchmarks/garage_benchmarks/experiments/algos/her_garage_tf.py
  benchmarks/garage_benchmarks/experiments/algos/ppo_garage_pytorch.py
  benchmarks/garage_benchmarks/experiments/algos/ppo_garage_tf.py
  benchmarks/garage_benchmarks/experiments/algos/td3_garage_tf.py
  benchmarks/garage_benchmarks/experiments/algos/trpo_garage_pytorch.py
  benchmarks/garage_benchmarks/experiments/algos/trpo_garage_tf.py
  benchmarks/garage_benchmarks/experiments/algos/vpg_garage_pytorch.py
  benchmarks/garage_benchmarks/experiments/algos/vpg_garage_tf.py
  benchmarks/garage_benchmarks/experiments/baselines/__init__.py
  benchmarks/garage_benchmarks/experiments/baselines/continuous_mlp_baseline_tf.py
  benchmarks/garage_benchmarks/experiments/baselines/gaussian_cnn_baseline_tf.py
  benchmarks/garage_benchmarks/experiments/baselines/gaussian_mlp_baseline_tf.py
  benchmarks/garage_benchmarks/helper.py
  benchmarks/garage_benchmarks/parameters.py
  benchmarks/garage_benchmarks/setup.py
Labels: ready-to-merge

#1412 Update all examples to not use run_experiment
  examples/jupyter/custom_env.ipynb
  examples/jupyter/trpo_gym_tf_cartpole.ipynb
  examples/np/cma_es_cartpole.py
  examples/tf/dqn_cartpole.py
  examples/tf/dqn_pong.py
  examples/tf/her_ddpg_fetchreach.py
  examples/tf/multi_env_ppo.py
  examples/tf/multi_env_trpo.py
  examples/tf/ppo_memorize_digits.py
  examples/tf/reps_gym_cartpole.py
  examples/tf/td3_pendulum.py
  examples/tf/trpo_cartpole.py
  examples/tf/trpo_cartpole_batch_sampler.py
  examples/tf/trpo_cubecrash.py
  examples/tf/trpo_gym_tf_cartpole.py
  examples/tf/trpo_swimmer.py
  examples/tf/trpois_inverted_pendulum.py
  examples/tf/vpg_cartpole.py
  examples/tf/vpgis_inverted_pendulum.py
  examples/torch/ddpg_pendulum.py
  examples/torch/trpo_pendulum.py
  examples/torch/vpg_pendulum.py
Labels: ready-to-merge

#1396 Make wrap_exp's archiving handle deleted files
  src/garage/experiment/experiment.py
  tests/garage/experiment/test_experiment.py
Labels: ready-to-merge

#1325 Create a 'benchmarks' extra, separate from 'dev'
  benchmarks/setup.py
  setup.py
  src/garage/replay_buffer/replay_buffer.py
  src/garage/torch/optimizers/optimizer_wrapper.py
  tests/benchmark_helper.py
  tests/fixtures/sampler/ray_fixtures.py
  tests/helpers.py
Labels: needs force push

#1408 Add run script for benchmarking
  benchmarks/setup.py
  benchmarks/src/garage_benchmarks/benchmark_auto.py
  benchmarks/src/garage_benchmarks/run_benchmarks.py
Labels: ready-to-merge

#1419 Fix pixel normalization in CNN Q functions
  src/garage/tf/policies/discrete_qf_derived_policy.py
  src/garage/tf/q_functions/continuous_cnn_q_function.py
  src/garage/tf/q_functions/discrete_cnn_q_function.py
  tests/garage/tf/q_functions/test_continuous_cnn_q_function.py
  tests/garage/tf/q_functions/test_discrete_cnn_q_function.py
Labels: needs backport, ready-to-merge

#1414 Add function to upload auto benchmarking result to GCP
  .pre-commit-config.yaml
  .pylintrc
  benchmarks/setup.py
  benchmarks/src/garage_benchmarks/helper.py
Labels: ready-to-merge

#1413 Doc modernization
  docs/index.rst
  docs/user/experiments.rst
  docs/user/implement_algo.rst
  docs/user/implement_algo_advanced.rst
  docs/user/implement_algo_basic.rst
  docs/user/implement_env.rst
  docs/user/installation.rst
  src/garage/np/algos/rl_algorithm.py
Labels: ready-to-merge

#1397 Make ExplorationStrategies a type of Policy
  benchmarks/src/garage_benchmarks/experiments/algos/ddpg_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/algos/her_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/algos/td3_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/policies/continuous_mlp_policy.py
  benchmarks/src/garage_benchmarks/experiments/q_functions/continuous_mlp_q_function.py
  examples/tf/ddpg_pendulum.py
  examples/tf/dqn_cartpole.py
  examples/tf/dqn_pong.py
  examples/tf/her_ddpg_fetchreach.py
  examples/tf/td3_pendulum.py
  examples/torch/ddpg_pendulum.py
  src/garage/np/algos/off_policy_rl_algorithm.py
  src/garage/np/exploration_policies/__init__.py
  src/garage/np/exploration_policies/add_gaussian_noise.py
  src/garage/np/exploration_policies/add_ornstein_uhlenbeck_noise.py
  src/garage/np/exploration_policies/epsilon_greedy_policy.py
  src/garage/np/exploration_policies/exploration_policy.py
  src/garage/np/exploration_strategies/__init__.py
  src/garage/np/exploration_strategies/exploration_strategy.py
  src/garage/np/exploration_strategies/gaussian_strategy.py
  src/garage/sampler/off_policy_vectorized_sampler.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  tests/garage/np/exploration_strategies/__init__.py
  tests/garage/np/exploration_strategies/test_add_gaussian_noise.py
  tests/garage/np/exploration_strategies/test_epsilon_greedy_policy.py
  tests/garage/sampler/test_off_policy_vectorized_sampler_integration.py
  tests/garage/tf/algos/test_ddpg.py
  tests/garage/tf/algos/test_dqn.py
  tests/garage/tf/algos/test_td3.py
  tests/garage/torch/algos/test_ddpg.py
Labels: ready-to-merge

#1428 Make @ahtsan owner of the TF tree
  CODEOWNERS
Labels: ready-to-merge

#1429 Mention OS support in README.md
  README.md
Labels: ready-to-merge

#1430 Extend 2019.10 maintenance window
  README.md
Labels: ready-to-merge

#1432 Fix benchmark imports
  benchmarks/src/garage_benchmarks/experiments/policies/continuous_mlp_policy.py
  benchmarks/src/garage_benchmarks/experiments/q_functions/continuous_mlp_q_function.py
Labels: ready-to-merge

#1431 Use `nproc` workers for local tests
  Makefile
Labels: ready-to-merge

#1444 Fix old and new distribution synchronization in on-policy algorithms
  src/garage/tf/algos/_rl2npo.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  tests/garage/tf/algos/test_rl2ppo.py
Labels: bug, ready-to-merge

#1458 Temporarily disable pipenv job
  Makefile
Labels: ready-to-merge

#1481 Document using pip install --user by default
  docs/user/installation.rst
Labels: ready-to-merge

#1484 Use pip install --user in README.md
  README.md
Labels: ready-to-merge

#1485 Remove codecov-patch condition from mergify
  .mergify.yml
Labels: ready-to-merge
