Repository rlworkgroup/garage, pull requests merged in 2020-08, with the labels that each got.

#1775 Define garage.Environment API
  src/garage/__init__.py
  src/garage/_environment.py
  src/garage/envs/dm_control/dm_control_env.py
  src/garage/envs/env_spec.py
  tests/garage/envs/test_env_spec.py
Labels: ready-to-merge

#1605 Torch discrete CNN policy
  src/garage/torch/__init__.py
  src/garage/torch/_functions.py
  src/garage/torch/modules/__init__.py
  src/garage/torch/modules/categorical_cnn_module.py
  src/garage/torch/modules/cnn_module.py
  src/garage/torch/modules/multi_headed_mlp_module.py
  src/garage/torch/policies/__init__.py
  src/garage/torch/policies/categorical_cnn_policy.py
  src/garage/torch/policies/deterministic_mlp_policy.py
  src/garage/torch/policies/stochastic_policy.py
  tests/garage/torch/modules/__init__.py
  tests/garage/torch/modules/test_categorical_cnn_module.py
  tests/garage/torch/modules/test_cnn_module.py
  tests/garage/torch/policies/test_categorical_cnn_policy.py
  tests/garage/torch/test_functions.py
Labels: ready-to-merge

#1835 Fix rendering mujoco to pixels in docker
  docker/Dockerfile
Labels: backport-to-2020.06, ready-to-merge

#1821 Add tfp SeedStream
  src/garage/experiment/deterministic.py
  src/garage/tf/algos/te_npo.py
  src/garage/tf/distributions/diagonal_gaussian.py
  src/garage/tf/embeddings/gaussian_mlp_encoder.py
  src/garage/tf/models/categorical_cnn_model.py
  src/garage/tf/models/categorical_gru_model.py
  src/garage/tf/models/categorical_lstm_model.py
  src/garage/tf/models/categorical_mlp_model.py
  src/garage/tf/models/cnn.py
  src/garage/tf/models/cnn_mlp_merge_model.py
  src/garage/tf/models/cnn_model.py
  src/garage/tf/models/cnn_model_max_pooling.py
  src/garage/tf/models/gaussian_cnn_model.py
  src/garage/tf/models/gaussian_gru_model.py
  src/garage/tf/models/gaussian_lstm_model.py
  src/garage/tf/models/gaussian_mlp_model.py
  src/garage/tf/models/gru_model.py
  src/garage/tf/models/lstm_model.py
  src/garage/tf/models/mlp.py
  src/garage/tf/models/mlp_dueling_model.py
  src/garage/tf/models/mlp_merge_model.py
  src/garage/tf/models/mlp_model.py
  src/garage/tf/models/normalized_input_mlp_model.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/tf/q_functions/continuous_cnn_q_function.py
  src/garage/tf/q_functions/continuous_mlp_q_function.py
  src/garage/tf/q_functions/discrete_cnn_q_function.py
  src/garage/tf/q_functions/discrete_mlp_q_function.py
  src/garage/tf/regressors/bernoulli_mlp_regressor.py
  src/garage/tf/regressors/categorical_mlp_regressor.py
  src/garage/tf/regressors/categorical_mlp_regressor_model.py
  src/garage/tf/regressors/continuous_mlp_regressor.py
  src/garage/tf/regressors/gaussian_cnn_regressor.py
  src/garage/tf/regressors/gaussian_cnn_regressor_model.py
  src/garage/tf/regressors/gaussian_mlp_regressor.py
  src/garage/tf/regressors/gaussian_mlp_regressor_model.py
  tests/garage/tf/regressors/test_gaussian_cnn_regressor.py
Labels: ready-to-merge

#1786 Add StepType and remove terminal
  src/garage/__init__.py
  src/garage/_dtypes.py
  src/garage/_functions.py
  src/garage/replay_buffer/path_buffer.py
  src/garage/sampler/_dtypes.py
  src/garage/sampler/default_worker.py
  src/garage/sampler/fragment_worker.py
  src/garage/sampler/vec_worker.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/te.py
  src/garage/torch/algos/pearl.py
  src/garage/torch/algos/sac.py
  tests/garage/sampler/test_fragment_worker.py
  tests/garage/test_dtypes.py
  tests/garage/test_functions.py
  tests/garage/torch/policies/test_context_conditioned_policy.py
Labels: ready-to-merge

#1840 Use cudnn7-runtime for run-nvidia (#1807)
  Makefile
  docker/hooks/build
Labels: ready-to-merge

#1802 Documentation on running ML/ MT RL experiments
  docs/index.md
  docs/user/meta_multi_task_rl_exp.md
Labels: documentation, ready-to-merge

#1822 Copy parameters when cloning
  src/garage/experiment/local_tf_runner.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/te_npo.py
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/embeddings/encoder.py
  src/garage/tf/embeddings/gaussian_mlp_encoder.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/tf/q_functions/continuous_cnn_q_function.py
  src/garage/tf/q_functions/continuous_mlp_q_function.py
  src/garage/tf/q_functions/discrete_cnn_q_function.py
  src/garage/tf/q_functions/discrete_mlp_dueling_q_function.py
  src/garage/tf/q_functions/discrete_mlp_q_function.py
  tests/garage/tf/baselines/test_gaussian_cnn_baseline.py
  tests/garage/tf/baselines/test_gaussian_mlp_baseline.py
  tests/garage/tf/embeddings/test_gaussian_mlp_encoder.py
  tests/garage/tf/policies/test_categorical_cnn_policy.py
  tests/garage/tf/policies/test_categorical_gru_policy.py
  tests/garage/tf/policies/test_categorical_lstm_policy.py
  tests/garage/tf/policies/test_categorical_mlp_policy.py
  tests/garage/tf/policies/test_gaussian_gru_policy.py
  tests/garage/tf/policies/test_gaussian_lstm_policy.py
  tests/garage/tf/policies/test_gaussian_mlp_policy.py
  tests/garage/tf/q_functions/test_continuous_cnn_q_function.py
  tests/garage/tf/q_functions/test_continuous_mlp_q_function.py
  tests/garage/tf/q_functions/test_discrete_cnn_q_function.py
  tests/garage/tf/q_functions/test_discrete_mlp_q_function.py
Labels: backport-to-2019.10, backport-to-2020.06

#1815 Fix TimeLimit inconsistency
  src/garage/envs/bullet/bullet_env.py
  src/garage/envs/garage_env.py
  src/garage/sampler/vec_worker.py
  tests/garage/sampler/test_fragment_worker.py
Labels: backport-to-2020.06, ready-to-merge

#1836 Add Github Actions for Pre-Commit Testing
  .github/workflows/ci.yml
Labels: ready-to-merge

#1854 Include bib file in docs rule
  .mergify.yml
Labels: needs force push, ready-to-merge

#1852 Backport #1815 to release-2020.06
  src/garage/envs/garage_env.py
  src/garage/sampler/vec_worker.py
Labels: ready-to-merge

#1788 Doc for implementing an algorithm using tf and np.
  docs/user/implement_algo.md
  docs/user/implement_algo.rst
  docs/user/implement_env.rst
  docs/user/implement_worker.md
  docs/user/references.bib
  docs/user/testing.md
  docs/user/training_a_policy.md
  examples/np/tutorial_cem.py
  examples/tf/tutorial_vpg.py
  examples/torch/tutorial_vpg.py
  src/garage/_dtypes.py
Labels: ready-to-merge

#1715 Backport #1617 to release-2019.10
  examples/tf/her_ddpg_fetchreach.py
  src/garage/sampler/utils.py
  tests/fixtures/policies/dummy_policy.py
  tests/garage/sampler/test_utils.py
Labels: ready-to-merge

#1809 Add Creating a PR doc
  docs/index.md
  docs/user/preparing_a_pr.md
Labels: documentation, ready-to-merge

#1857 Include bib file in checking docs PR
  scripts/travisci/check_docs_only.sh
Labels: ready-to-merge

#1817 Add doc for custom worker
  docs/index.md
  docs/user/custom_worker.md
  docs/user/references.bib
Labels: documentation, ready-to-merge

#1828 Add doc for maximizing resources usage
  docs/index.md
  docs/user/max_resource_usage.md
Labels: documentation, ready-to-merge

#1844 Normalize image observation of input in GaussianCNNBaseline.
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  tests/garage/tf/baselines/test_gaussian_cnn_baseline.py
Labels: ready-to-merge

#1855 Backport #1822
  src/garage/experiment/local_tf_runner.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/te_npo.py
  src/garage/tf/embeddings/encoder.py
  src/garage/tf/embeddings/gaussian_mlp_encoder.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/tf/q_functions/continuous_cnn_q_function.py
  src/garage/tf/q_functions/continuous_mlp_q_function.py
  src/garage/tf/q_functions/discrete_cnn_q_function.py
  src/garage/tf/q_functions/discrete_mlp_q_function.py
  src/garage/tf/regressors/gaussian_mlp_regressor_model.py
  tests/garage/tf/policies/test_categorical_cnn_policy.py
  tests/garage/tf/policies/test_categorical_gru_policy.py
  tests/garage/tf/policies/test_categorical_lstm_policy.py
  tests/garage/tf/policies/test_categorical_mlp_policy.py
  tests/garage/tf/policies/test_gaussian_gru_policy.py
  tests/garage/tf/policies/test_gaussian_lstm_policy.py
  tests/garage/tf/policies/test_gaussian_mlp_policy.py
  tests/garage/tf/q_functions/test_continuous_cnn_q_function.py
  tests/garage/tf/q_functions/test_continuous_mlp_q_function.py
  tests/garage/tf/q_functions/test_discrete_cnn_q_function.py
  tests/garage/tf/q_functions/test_discrete_mlp_q_function.py
Labels: ready-to-merge

#1826 Request review from contributors only once
  .mergify.yml
Labels: needs force push, ready-to-merge

#1874 Request contributor reviews once (#1826 follow-up)
  .mergify.yml
Labels: needs force push, ready-to-merge

#1871 Print frozen deps in the CI
  Makefile
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1878 Relax test_trpo_gru_cartpole
  tests/garage/tf/algos/test_trpo.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1782 Docs for starting a new experiment with a pretrained network
  docs/index.md
  docs/user/use_pretrained_network_to_start_new_experiment.md
Labels: documentation, ready-to-merge

#1885 Backport #1878
  tests/garage/tf/algos/test_trpo.py
Labels: ready-to-merge

#1884 Backport #1878
  tests/garage/tf/algos/test_trpo.py
Labels: ready-to-merge

#1877 Suppress physics errors in dm_control tests
  tests/garage/envs/dm_control/test_dm_control_env.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1879 Unpin TensorFlow
  docs/requirements.txt
  setup.py
  tests/garage/tf/algos/test_dqn.py
Labels: backport-to-2020.06, ready-to-merge

#1889 Backport #1879
  docs/requirements.txt
  setup.py
Labels: ready-to-merge

#1888 Fix for #1856
  .github/workflows/ci.yml
Labels: ready-to-merge

#1812 Flatten observations in the policy if needed
  CHANGELOG.md
  docs/user/implement_algo.md
  docs/user/meta_multi_task_rl_exp.md
  docs/user/training_a_policy.md
  docs/user/use_pretrained_network_to_start_new_experiment.md
  examples/jupyter/custom_env.ipynb
  examples/tf/trpo_swimmer_ray_sampler.py
  examples/torch/trpo_pendulum_ray_sampler.py
  src/garage/np/policies/__init__.py
  src/garage/sampler/utils.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/discrete_qf_derived_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/torch/policies/categorical_cnn_policy.py
  src/garage/torch/policies/deterministic_mlp_policy.py
  src/garage/torch/policies/stochastic_policy.py
  tests/fixtures/envs/dummy/dummy_dict_env.py
  tests/fixtures/q_functions/simple_q_function.py
  tests/fixtures/sampler/ray_fixtures.py
  tests/garage/replay_buffer/test_her_replay_buffer.py
  tests/garage/sampler/test_utils.py
  tests/garage/tf/policies/test_categorical_cnn_policy.py
  tests/garage/tf/policies/test_categorical_gru_policy.py
  tests/garage/tf/policies/test_categorical_lstm_policy.py
  tests/garage/tf/policies/test_categorical_mlp_policy.py
  tests/garage/tf/policies/test_continuous_mlp_policy.py
  tests/garage/tf/policies/test_gaussian_gru_policy.py
  tests/garage/tf/policies/test_gaussian_lstm_policy.py
  tests/garage/tf/policies/test_gaussian_mlp_policy.py
  tests/garage/tf/policies/test_qf_derived_policy.py
  tests/garage/torch/policies/test_categorical_cnn_policy.py
  tests/garage/torch/policies/test_context_conditioned_policy.py
  tests/garage/torch/policies/test_deterministic_mlp_policy.py
  tests/garage/torch/policies/test_gaussian_mlp_policy.py
  tests/garage/torch/policies/test_tanh_gaussian_mlp_policy.py
  tests/integration_tests/test_examples.py
Labels: backport-to-2020.06, ready-to-merge

#1897 Fix EnvStep comparison and tests
  examples/tf/rl2_ppo_metaworld_ml10.py
  examples/tf/rl2_ppo_metaworld_ml10_meta_test.py
  examples/tf/rl2_ppo_metaworld_ml45.py
  examples/tf/trpo_swimmer_ray_sampler.py
  examples/torch/trpo_pendulum_ray_sampler.py
  src/garage/_environment.py
  src/garage/envs/gym_env.py
  tests/fixtures/sampler/ray_fixtures.py
  tests/garage/tf/envs/test_gym_base.py
  tests/helpers.py
Labels: ready-to-merge

#1899 Update torch.full for torch 1.7 support
  src/garage/torch/_functions.py
  tests/garage/torch/modules/test_gaussian_mlp_module.py
  tests/garage/torch/modules/test_multi_headed_mlp_module.py
  tests/garage/torch/policies/test_gaussian_mlp_policy.py
  tests/garage/torch/policies/test_tanh_gaussian_mlp_policy.py
Labels: backport-to-2020.06, ready-to-merge

#1766 Support all registered bullet gym envs
  src/garage/envs/bullet/__init__.py
  src/garage/envs/bullet/bullet_env.py
  src/garage/envs/gym_env.py
  tests/garage/envs/bullet/test_bullet_env.py
  tests/garage/tf/envs/test_gym_base.py
Labels: ready-to-merge

#1910 Fix nightly tests
  setup.py
  src/garage/envs/gym_env.py
  src/garage/tf/algos/rl2.py
  tests/garage/tf/envs/test_gym_base.py
Labels: ready-to-merge

#1914 Add missing backslash in Makefile
  Makefile
Labels: ready-to-merge

#1907 fix rollout episode termination logic
  src/garage/_dtypes.py
  src/garage/sampler/default_worker.py
  src/garage/sampler/utils.py
  tests/garage/test_dtypes.py
Labels: ready-to-merge

#1918 Update CHANGELOG for v2019.10.3
  CHANGELOG.md
Labels: ready-to-merge

#1919 Update CHANGELOG for v2020.06.2
  CHANGELOG.md
Labels: ready-to-merge

#1902 Update broken benchmarks
  benchmarks/src/garage_benchmarks/experiments/algos/ddpg_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/algos/her_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/algos/td3_garage_tf.py
Labels: ready-to-merge

#1915 Pin gym version in benchmarks package
  benchmarks/setup.py
Labels: backport-to-2020.06, ready-to-merge

#1928 Deflake test_trpo_lstm_cartpole
  tests/garage/tf/algos/test_trpo.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1920 Fix argument name in tests
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1901 Remove merge statements in docs and examples
  docs/user/implement_algo.md
  docs/user/meta_multi_task_rl_exp.md
  docs/user/training_a_policy.md
  docs/user/use_pretrained_network_to_start_new_experiment.md
  examples/jupyter/custom_env.ipynb
Labels: ready-to-merge

#1927 Return unscaled action in normalize wrapper
  src/garage/envs/normalized_env.py
Labels: ready-to-merge

#1861 Run test suites with GitHub Actions
  .github/workflows/ci.yml
  docker/Dockerfile
  tests/garage/tf/algos/test_ppo.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1944 Relax test_ppo_pendulum_lstm
  tests/garage/tf/algos/test_ppo.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1905 Update mtsac_metaworld_mt50.py
  examples/torch/mtsac_metaworld_mt50.py
Labels: backport-to-2020.06, ready-to-merge

#1934 Backport 2020.06 for torch support 1.7
  src/garage/torch/_functions.py
  tests/garage/tf/policies/test_gaussian_mlp_policy.py
  tests/garage/torch/modules/test_gaussian_mlp_module.py
  tests/garage/torch/modules/test_multi_headed_mlp_module.py
  tests/garage/torch/policies/test_gaussian_mlp_policy.py
  tests/garage/torch/policies/test_tanh_gaussian_mlp_policy.py
Labels: ready-to-merge

#1908 Use max episode length eval in SAC evaluation
  examples/torch/sac_half_cheetah_batch.py
  src/garage/torch/algos/sac.py
Labels: backport-to-2020.06, ready-to-merge

#1951 Add Slack and garage-announce to README
  README.md
Labels: ready-to-merge

#1960 Fix test env pickleable
  tests/garage/tf/envs/test_base.py
Labels: ready-to-merge

#1959 Fix footer images in docs
  docs/_templates/footer.html
Labels: ready-to-merge

#1956 Remove upper constraint for torch version
  setup.py
Labels: backport-to-2020.06, ready-to-merge

#1963 Backport #1956
  setup.py
Labels: ready-to-merge

#1942 Fix LocalRunner always use RLAlgorithm.worker_cls
  src/garage/experiment/local_runner.py
  src/garage/torch/algos/sac.py
Labels: backport-to-2020.06, ready-to-merge

#1962 Increase example test timeout for GH actions
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1968 Allow deterministic=False for off-policy
  src/garage/np/_functions.py
  src/garage/torch/algos/sac.py
Labels: ready-to-merge

#1965 Set docker memory limit to 6.5gb
  .github/workflows/ci.yml
Labels: needs force push, ready-to-merge

#1976 Use GH Actions as the only blocking CI on master
  .mergify.yml
Labels: ready-to-merge

#1964 Remove upper constraint for torchvision version
  setup.py
Labels: backport-to-2020.06, ready-to-merge

#1977 Rename max_episode_length in FirstOrderOptimizer
  benchmarks/src/garage_benchmarks/experiments/algos/ppo_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/baselines/continuous_mlp_baseline.py
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_cnn_baseline.py
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_mlp_baseline.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_cnn_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_gru_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_lstm_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_mlp_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_gru_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_lstm_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_mlp_policy.py
  docs/user/meta_multi_task_rl_exp.md
  examples/tf/multi_env_ppo.py
  examples/tf/ppo_memorize_digits.py
  examples/tf/ppo_pendulum.py
  examples/tf/rl2_ppo_halfcheetah.py
  examples/tf/rl2_ppo_halfcheetah_meta_test.py
  examples/tf/rl2_ppo_metaworld_ml10.py
  examples/tf/rl2_ppo_metaworld_ml10_meta_test.py
  examples/tf/rl2_ppo_metaworld_ml1_push.py
  examples/tf/rl2_ppo_metaworld_ml45.py
  examples/tf/te_ppo_metaworld_ml1_push.py
  examples/tf/te_ppo_metaworld_mt10.py
  examples/tf/te_ppo_metaworld_mt50.py
  examples/tf/te_ppo_point.py
  src/garage/tf/algos/te_ppo.py
  src/garage/tf/algos/vpg.py
  src/garage/tf/optimizers/first_order_optimizer.py
  tests/garage/tf/algos/test_ppo.py
  tests/garage/tf/algos/test_rl2ppo.py
  tests/garage/tf/algos/test_te.py
Labels: ready-to-merge

#1975 Various MTSAC bug fixes
  examples/torch/mtsac_metaworld_ml1_pick_place.py
  examples/torch/mtsac_metaworld_mt10.py
  examples/torch/mtsac_metaworld_mt50.py
  src/garage/torch/algos/mtsac.py
  src/garage/torch/algos/sac.py
  tests/garage/torch/algos/test_mtsac.py
Labels: ready-to-merge

#1984 Backport (#1942) for release-2020.06
  src/garage/experiment/local_runner.py
  src/garage/torch/algos/sac.py
Labels: ready-to-merge

#1875 Update implement env doc
  docs/conf.py
  docs/user/implement_env.md
  docs/user/implement_env.rst
Labels: ready-to-merge

#1986 Fix testing env pickleable
  tests/helpers.py
Labels: ready-to-merge
