Repository rlworkgroup/garage, pull requests merged in 2020-06, with the labels that each got.

#1493 Remove garage.np.regressors
  src/garage/np/regressors/__init__.py
  src/garage/np/regressors/product_regressor.py
Labels: ready-to-merge

#1492 Delete np/batch_polopt.py
  src/garage/np/algos/__init__.py
  src/garage/np/algos/batch_polopt.py
  tests/fixtures/algos/dummy_algo.py
Labels: ready-to-merge

#1495 Remove garage.misc.prog_bar_counter and pyprind
  setup.py
  src/garage/misc/prog_bar_counter.py
  src/garage/sampler/multiprocessing_sampler.py
  src/garage/sampler/on_policy_vectorized_sampler.py
  src/garage/sampler/ray_sampler.py
  src/garage/sampler/stateful_pool.py
  src/garage/tf/optimizers/first_order_optimizer.py
Labels: ready-to-merge

#1456 Refactor GaussianMLPBaseline to use tfp
  src/garage/tf/embeddings/gaussian_mlp_encoder.py
  src/garage/tf/models/__init__.py
  src/garage/tf/models/gaussian_mlp_model.py
  src/garage/tf/models/gaussian_mlp_model2.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/tf/regressors/gaussian_mlp_regressor.py
  src/garage/tf/regressors/gaussian_mlp_regressor_model.py
  tests/garage/tf/models/test_gaussian_mlp_model.py
  tests/garage/tf/regressors/test_gaussian_mlp_regressor.py
Labels: ready-to-merge

#1504 Remove tf batchpolopt
  src/garage/np/algos/cem.py
  src/garage/np/algos/cma_es.py
  src/garage/tf/__init__.py
  src/garage/tf/_functions.py
  src/garage/tf/algos/__init__.py
  src/garage/tf/algos/_rl2npo.py
  src/garage/tf/algos/batch_polopt.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/rl2.py
  tests/fixtures/algos/dummy_tf_algo.py
  tests/fixtures/experiment/fixture_experiment.py
  tests/fixtures/tf/algos/dummy_off_policy_algo.py
  tests/fixtures/tf/instrumented_batch_polopt.py
  tests/garage/tf/algos/test_batch_polopt.py
  tests/garage/torch/policies/test_gaussian_mlp_policy.py
Labels: ready-to-merge

#1510 Ensure TF and torch are optional
  src/garage/experiment/meta_evaluator.py
  src/garage/sampler/__init__.py
  src/garage/sampler/is_sampler.py
  src/garage/sampler/parallel_sampler.py
Labels: ready-to-merge

#1460 Fix pipenv install on CI
  .dockerignore
  Makefile
  tests/garage/tf/algos/test_rl2ppo.py
Labels: needs backport, ready-to-merge

#1516 Remove itr param from optimize_policy()
  src/garage/np/algos/nop.py
  src/garage/np/algos/off_policy_rl_algorithm.py
  src/garage/tf/algos/_rl2npo.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/rl2.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  src/garage/torch/algos/sac.py
  tests/fixtures/algos/dummy_tf_algo.py
  tests/fixtures/tf/algos/dummy_off_policy_algo.py
Labels: ready-to-merge

#1496 New optimizer_args tf interface + test optimizer type
  benchmarks/src/garage_benchmarks/experiments/algos/ppo_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/algos/vpg_garage_tf.py
  benchmarks/src/garage_benchmarks/experiments/baselines/continuous_mlp_baseline.py
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_cnn_baseline.py
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_mlp_baseline.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_cnn_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_gru_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_lstm_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_mlp_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_gru_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_lstm_policy.py
  benchmarks/src/garage_benchmarks/experiments/policies/gaussian_mlp_policy.py
  examples/tf/multi_env_ppo.py
  examples/tf/ppo_memorize_digits.py
  examples/tf/vpg_cartpole.py
  src/garage/__init__.py
  src/garage/_functions.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/td3.py
  src/garage/tf/optimizers/first_order_optimizer.py
  src/garage/tf/regressors/bernoulli_mlp_regressor.py
  src/garage/tf/regressors/categorical_mlp_regressor.py
  src/garage/tf/regressors/continuous_mlp_regressor.py
  src/garage/tf/regressors/gaussian_cnn_regressor.py
  src/garage/tf/regressors/gaussian_mlp_regressor.py
  src/garage/torch/__init__.py
  src/garage/torch/_utils.py
  src/garage/torch/algos/__init__.py
  src/garage/torch/algos/ddpg.py
  src/garage/torch/algos/maml.py
  src/garage/torch/algos/maml_ppo.py
  src/garage/torch/algos/maml_trpo.py
  src/garage/torch/algos/maml_vpg.py
  src/garage/torch/algos/vpg.py
  src/garage/torch/optimizers/optimizer_wrapper.py
  tests/fixtures/experiment/fixture_experiment.py
  tests/garage/test_functions.py
  tests/garage/tf/algos/test_ppo.py
  tests/garage/tf/algos/test_vpg.py
  tests/garage/tf/experiment/test_local_tf_runner.py
  tests/garage/tf/misc/test_tensor_utils.py
  tests/garage/torch/algos/test_torch_algo_utils.py
Labels: ready-to-merge

#1521 Mark test_mtsac_inverted_double_pendulum as flaky
  tests/garage/torch/algos/test_mtsac.py
Labels: ready-to-merge

#1515 Change CNN API to use tuples for defining kernels
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_cnn_baseline.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_cnn_policy.py
  examples/tf/dqn_pong.py
  examples/tf/ppo_memorize_digits.py
  examples/tf/trpo_cubecrash.py
  src/garage/tf/models/categorical_cnn_model.py
  src/garage/tf/models/cnn.py
  src/garage/tf/models/cnn_mlp_merge_model.py
  src/garage/tf/models/cnn_model.py
  src/garage/tf/models/cnn_model_max_pooling.py
  src/garage/tf/models/gaussian_cnn_model.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/q_functions/continuous_cnn_q_function.py
  src/garage/tf/q_functions/discrete_cnn_q_function.py
  src/garage/tf/regressors/gaussian_cnn_regressor.py
  src/garage/tf/regressors/gaussian_cnn_regressor_model.py
  tests/fixtures/models/simple_cnn_model.py
  tests/fixtures/models/simple_cnn_model_with_max_pooling.py
  tests/garage/tf/algos/test_trpo.py
  tests/garage/tf/models/test_categorical_cnn_model.py
  tests/garage/tf/models/test_cnn.py
  tests/garage/tf/models/test_cnn_mlp_merge_model.py
  tests/garage/tf/models/test_cnn_model.py
  tests/garage/tf/models/test_gaussian_cnn_model.py
  tests/garage/tf/policies/test_categorical_cnn_policy.py
  tests/garage/tf/q_functions/test_continuous_cnn_q_function.py
  tests/garage/tf/q_functions/test_discrete_cnn_q_function.py
  tests/garage/tf/regressors/test_gaussian_cnn_regressor.py
  tests/helpers.py
Labels: ready-to-merge

#1505 Implement HER using PathBuffer
  benchmarks/src/garage_benchmarks/experiments/algos/her_garage_tf.py
  examples/tf/her_ddpg_fetchreach.py
  src/garage/replay_buffer/__init__.py
  src/garage/replay_buffer/her_replay_buffer.py
  src/garage/replay_buffer/path_buffer.py
  src/garage/replay_buffer/simple_replay_buffer.py
  src/garage/sampler/off_policy_vectorized_sampler.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  tests/garage/replay_buffer/test_her_replay_buffer.py
  tests/garage/replay_buffer/test_replay_buffer.py
Labels: ready-to-merge

#1554 Fix tf plotter policy build
  src/garage/tf/plotter/plotter.py
Labels: needs backport

#1529 Add TimeStepBatch
  src/garage/__init__.py
  src/garage/_dtypes.py
  tests/garage/test_dtypes.py
Labels: ready-to-merge

#1528 Refactor torch policies
  src/garage/torch/algos/maml.py
  src/garage/torch/algos/ppo.py
  src/garage/torch/algos/sac.py
  src/garage/torch/algos/trpo.py
  src/garage/torch/algos/vpg.py
  src/garage/torch/policies/context_conditioned_policy.py
  src/garage/torch/policies/deterministic_mlp_policy.py
  src/garage/torch/policies/gaussian_mlp_policy.py
  src/garage/torch/policies/policy.py
  src/garage/torch/policies/stochastic_policy.py
  src/garage/torch/policies/tanh_gaussian_mlp_policy.py
  tests/garage/torch/algos/test_sac.py
  tests/garage/torch/policies/test_gaussian_mlp_policy.py
  tests/garage/torch/policies/test_tanh_gaussian_mlp_policy.py
Labels: ready-to-merge

#1563 Pin TensorFlow to >=1.14
  setup.py
Labels: ready-to-merge

#1424 Move to multi-stage docker builds
  .dockerignore
  .travis.yml
  Makefile
  docker/Dockerfile
  docker/Dockerfile.base.16.04
  docker/Dockerfile.base.18.04
  docker/entrypoint-headless.sh
  docker/entrypoint-runtime.sh
Labels: ready-to-merge

#1567 Handle non-deterministic mode in sampler workers
  src/garage/sampler/default_worker.py
  tests/garage/sampler/test_local_sampler.py
Labels: ready-to-merge

#1552 Refactor out OffPolicyRLAlgorithm
  src/garage/np/__init__.py
  src/garage/np/_functions.py
  src/garage/np/algos/__init__.py
  src/garage/np/algos/off_policy_rl_algorithm.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  src/garage/torch/algos/mtsac.py
  src/garage/torch/algos/sac.py
  tests/fixtures/tf/algos/dummy_off_policy_algo.py
  tests/garage/torch/algos/test_mtsac.py
Labels: ready-to-merge

#1579 Fix + update jupyter examples
  .gitignore
  examples/jupyter/custom_env.ipynb
  examples/jupyter/trpo_gym_tf_cartpole.ipynb
Labels: needs backport, ready-to-merge

#1577 Lower MTSAC Reward Threshold
  tests/garage/torch/algos/test_mtsac.py
Labels: ready-to-merge

#1584 Backport jupyter examples release-2019.10
  examples/jupyter/custom_env.ipynb
  examples/jupyter/trpo_gym_tf_cartpole.ipynb
Labels: ready-to-merge

#1582 Delete old docker-compose based Dockerfiles
  docker/Dockerfile.base.16.04
  docker/Dockerfile.base.18.04
  docker/Dockerfile.headless
  docker/Dockerfile.nvidia
  docker/Dockerfile.runtime
  docker/docker-compose-ci.yml
  docker/docker-compose-headless.yml
  docker/docker-compose-nvidia.yml
Labels: ready-to-merge

#1591 Refactoring CategoricalMLPRegressor with tfp
  src/garage/tf/regressors/categorical_mlp_regressor.py
  src/garage/tf/regressors/categorical_mlp_regressor_model.py
  tests/garage/tf/regressors/test_categorical_mlp_regressor.py
Labels: ready-to-merge

#1593 Remove cached_property dependency
  docs/requirements.txt
  setup.py
Labels: ready-to-merge

#1575 Update CHANGELOG.md for 2020.06.0 release
  CHANGELOG.md
Labels: ready-to-merge

#1597 Fix bug when calling CategoricalCNNPolicy
  benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_cnn_baseline.py
  benchmarks/src/garage_benchmarks/experiments/policies/categorical_cnn_policy.py
Labels: needs backport, ready-to-merge

#1588 Update setup_linux to ignore purge errors
  scripts/setup_linux.sh
Labels: ready-to-merge

#1559 Add PixelObservationWrapper
  src/garage/envs/wrappers/__init__.py
  src/garage/envs/wrappers/pixel_observation.py
  tests/garage/envs/wrappers/test_pixel_observation_wrapper.py
Labels: ready-to-merge

#1603 Export $USER in Dockerfile
  docker/Dockerfile
Labels: ready-to-merge

#1599 Recursively ignore data folder in dockerignore
  .dockerignore
Labels: needs backport, ready-to-merge

#1587 Drop python 3.5 support
  .travis.yml
  Makefile
  README.md
  docker/Dockerfile
  docs/user/installation.rst
  setup.py
  src/garage/torch/algos/sac.py
  tests/fixtures/envs/dummy/dummy_multitask_box_env.py
  tests/garage/experiment/test_experiment.py
  tests/garage/experiment/test_task_sampler.py
  tests/garage/tf/baselines/test_gaussian_cnn_baseline.py
  tests/garage/tf/models/test_model.py
  tests/helpers.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1598 Initialise GCP bucket only when needed
  benchmarks/src/garage_benchmarks/helper.py
Labels: ready-to-merge

#1592 Unify policy interface across the codebase
  src/garage/np/policies/__init__.py
  src/garage/np/policies/fixed_policy.py
  src/garage/np/policies/policy.py
  src/garage/np/policies/scripted_policy.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/td3.py
  src/garage/tf/models/module.py
  src/garage/tf/policies/policy.py
  src/garage/torch/policies/policy.py
  tests/fixtures/policies/dummy_policy.py
  tests/garage/tf/optimizers/__init__.py
  tests/garage/torch/policies/__init__.py
Labels: ready-to-merge

#1589 Add Pybullet support
  examples/step_bullet_kuka_env.py
  examples/tf/trpo_cartpole_bullet.py
  setup.py
  src/garage/envs/bullet/__init__.py
  src/garage/envs/bullet/bullet_env.py
  tests/garage/envs/bullet/__init__.py
  tests/garage/envs/bullet/test_bullet_env.py
Labels: ready-to-merge

#1610 Only run test jobs if pre-commit passes
  .travis.yml
Labels: ready-to-merge

#1612 Skip lengthy build steps for docs-only PRs
  .travis.yml
  scripts/travisci/check_docs_only.sh
Labels: ready-to-merge

#1578 Documentation on testing
  docs/user/testing.md
Labels: ready-to-merge

#1619 Only build Docker container for deps changes
  .travis.yml
  scripts/travisci/check_no_deps_changed.sh
Labels: ready-to-merge

#1618 Only run pipenv/conda checks in nightly builds
  .travis.yml
Labels: ready-to-merge

#1600 Add image observations doc
  docs/user/matplotlib_example.png
  docs/user/pixel_observations.md
Labels: ready-to-merge

#1608 Don't copy the eval env every epoch
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
Labels: needs backport, ready-to-merge

#1576 Make docker image smaller
  docker/Dockerfile
Labels: ready-to-merge

#1611 Prefer f-strings for string interpolation
  CONTRIBUTING.md
Labels: ready-to-merge

#1623 Add *.png to docs-only whitelist
  scripts/travisci/check_docs_only.sh
Labels: ready-to-merge

#1586 Add markdownlint to pre-commit
  .editorconfig
  .mdlrc
  .pre-commit-config.yaml
  docker/Dockerfile
  docs/user/testing.md
  scripts/setup_colab.sh
  scripts/setup_linux.sh
  scripts/setup_macos.sh
Labels: ready-to-merge

#1629 Delete .mdlrc
  .mdlrc
Labels: ready-to-merge

#1624 Add new docs pages to Table of Contents
  docs/conf.py
  docs/index.md
  docs/index.rst
  docs/user/api_reference.md
  docs/user/development_guide.md
  docs/user/pixel_observations.md
  docs/user/tutorials.md
  docs/user/usage_guide.md
Labels: documentation, ready-to-merge

#1628 Update dev VERSION
  VERSION
Labels: ready-to-merge

#1638 Acknowledge authors in documentation
  docs/user/experiments.rst
  docs/user/implement_algo.rst
  docs/user/implement_env.rst
  docs/user/installation.rst
  docs/user/pixel_observations.md
  docs/user/testing.md
Labels: documentation, ready-to-merge

#1604 Add documentation for benchmarking
  docs/user/benchmarking.md
  docs/user/development_guide.md
Labels: documentation, ready-to-merge

#1643 Better table of contents
  docs/index.md
  docs/user/api_reference.md
  docs/user/development_guide.md
  docs/user/tutorials.md
  docs/user/usage_guide.md
Labels: documentation, ready-to-merge

#1644 Fix table in benchmarking.md
  docs/user/benchmarking.md
Labels: documentation, ready-to-merge

#1646 Use mergify to automatically create backport PRs
  .mergify.yml
Labels: ready-to-merge

#1649 Set seed in TestERWR
  tests/garage/tf/algos/test_erwr.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#1659 Don't build backport branches
  .travis.yml
Labels: ready-to-merge

#1614 tf.Policy inherit from tf.Model
  src/garage/tf/algos/_rl2npo.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/td3.py
  src/garage/tf/algos/te_npo.py
  src/garage/tf/models/categorical_cnn_model.py
  src/garage/tf/models/categorical_gru_model.py
  src/garage/tf/models/categorical_lstm_model.py
  src/garage/tf/models/categorical_mlp_model.py
  src/garage/tf/models/model.py
  src/garage/tf/policies/__init__.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/discrete_qf_derived_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/tf/policies/policy.py
  src/garage/tf/policies/task_embedding_policy.py
  src/garage/tf/policies/uniform_control_policy.py
  src/garage/tf/regressors/gaussian_cnn_regressor_model.py
  tests/fixtures/models/simple_gaussian_cnn_model.py
  tests/fixtures/models/simple_gaussian_gru_model.py
  tests/fixtures/models/simple_gaussian_lstm_model.py
  tests/fixtures/models/simple_gaussian_mlp_model.py
  tests/fixtures/models/simple_gru_model.py
  tests/fixtures/models/simple_lstm_model.py
  tests/fixtures/models/simple_mlp_merge_model.py
  tests/fixtures/models/simple_mlp_model.py
  tests/garage/tf/models/test_categorical_gru_model.py
  tests/garage/tf/models/test_categorical_lstm_model.py
  tests/garage/tf/models/test_categorical_mlp_model.py
  tests/garage/tf/optimizers/test_conjugate_gradient_optimizer.py
  tests/garage/tf/policies/test_categorical_cnn_policy.py
  tests/garage/tf/policies/test_categorical_gru_policy.py
  tests/garage/tf/policies/test_categorical_lstm_policy.py
  tests/garage/tf/policies/test_categorical_mlp_policy.py
  tests/garage/tf/policies/test_continuous_mlp_policy.py
  tests/garage/tf/policies/test_gaussian_gru_policy.py
  tests/garage/tf/policies/test_gaussian_lstm_policy.py
  tests/garage/tf/policies/test_gaussian_mlp_policy.py
  tests/garage/tf/policies/test_gaussian_mlp_task_embedding_policy.py
Labels: API, tf

#1656 Fix typo in Makefile
  Makefile
Labels: backport-to-2020.06, ready-to-merge

#1663 Better API documentation
  .gitignore
  docker/Dockerfile
  docs/autoapi_templates/python/module.rst
  docs/conf.py
  docs/index.md
  docs/requirements.txt
  scripts/setup_colab.sh
  scripts/setup_linux.sh
  scripts/setup_macos.sh
  setup.py
Labels: documentation, ready-to-merge

#1640 Don't push to latest tag on DockerHub
  .travis.yml
  Makefile
  docker/Dockerfile.base.18.04
  docker/docker-compose-ci.yml
Labels: ready-to-merge

#1607 Behavioral Cloning
  examples/torch/bc_point.py
  examples/torch/bc_point_deterministic_policy.py
  src/garage/_dtypes.py
  src/garage/envs/point_env.py
  src/garage/experiment/local_runner.py
  src/garage/torch/__init__.py
  src/garage/torch/_functions.py
  src/garage/torch/algos/__init__.py
  src/garage/torch/algos/bc.py
  tests/garage/test_dtypes.py
  tests/garage/tf/algos/test_erwr.py
  tests/garage/torch/algos/test_bc.py
Labels: ready-to-merge

#1666 Remove remaining old-API sampler files
  src/garage/sampler/__init__.py
  src/garage/sampler/sampler_deprecated.py
  src/garage/sampler/vec_env_executor.py
Labels: ready-to-merge

#1622 Add doc for training a policy
  docs/index.md
  docs/user/benchmarking.md
  docs/user/training_a_policy.md
Labels: documentation, ready-to-merge

#1616 Add meta-documentation
  docs/index.md
  docs/user/writing_documentation.md
  src/garage/envs/wrappers/pixel_observation.py
Labels: documentation, ready-to-merge

#1667 Update testing.md
  docs/user/testing.md
Labels: ready-to-merge

#1660 Remove run_experiment
  scripts/garage
  src/garage/experiment/__init__.py
  src/garage/experiment/experiment.py
  src/garage/experiment/experiment_wrapper.py
  src/garage/experiment/local_tf_runner.py
  tests/garage/experiment/test_experiment.py
  tests/garage/experiment/test_experiment_wrapper.py
Labels: ready-to-merge
