Repository rlworkgroup/garage, pull requests merged in 2020-10, with the labels that each got.

#2086 Add mt-trpo doc
  docs/index.md
  docs/user/algo_mttrpo.md
Labels: documentation, ready-to-merge

#2088 Add DDPG doc
  docs/index.md
  docs/user/algo_ddpg.md
  docs/user/references.bib
Labels: documentation, ready-to-merge

#2070 Use TimeStepBatch in off policy algos in tf
  src/garage/_dtypes.py
  src/garage/replay_buffer/her_replay_buffer.py
  src/garage/replay_buffer/path_buffer.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  tests/garage/replay_buffer/test_path_buffer.py
  tests/garage/test_dtypes.py
Labels: ready-to-merge

#2090 Fix displaying tables in docs of algo
  docs/user/algo_bc.md
  docs/user/algo_ddpg.md
  docs/user/algo_mtppo.md
  docs/user/algo_mttrpo.md
  docs/user/algo_pearl.md
  docs/user/algo_ppo.md
  docs/user/algo_rl2.md
  docs/user/algo_sac.md
  docs/user/algo_td3.md
  docs/user/algo_trpo.md
  docs/user/algo_vpg.md
Labels: documentation, ready-to-merge

#2096 Fix pickling GymEnv
  src/garage/envs/gym_env.py
  tests/garage/envs/test_gym_env.py
Labels: ready-to-merge

#2092 Add ERWR doc
  docs/index.md
  docs/user/algo_erwr.md
  docs/user/references.bib
Labels: ready-to-merge

#2081 Use episode batch in tf/npo
  src/garage/_dtypes.py
  src/garage/np/baselines/linear_feature_baseline.py
  src/garage/tf/algos/_rl2npo.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/rl2.py
  tests/garage/test_dtypes.py
Labels: ready-to-merge

#2093 Add MAML doc
  docs/index.md
  docs/user/algo_maml.md
  docs/user/references.bib
Labels: ready-to-merge

#2085 Make snapshot_config optional in benchmarks
  benchmarks/src/garage_benchmarks/benchmark_auto.py
  benchmarks/src/garage_benchmarks/helper.py
Labels: ready-to-merge

#2041 Add doc for MTSAC algorithm
  docs/index.md
  docs/user/algo_mtsac.md
Labels: documentation, ready-to-merge

#2132 Fix #2131
  tests/garage/envs/test_normalized_gym.py
Labels: ready-to-merge

#2128 Allow setting x-axis in wrap_experiment
  src/garage/experiment/experiment.py
Labels: ready-to-merge

#2125 Record total_env_steps in samplers
  src/garage/sampler/local_sampler.py
  src/garage/sampler/multiprocessing_sampler.py
  src/garage/sampler/ray_sampler.py
Labels: ready-to-merge

#2094 Rerun failed tests once automatically on CI
  .github/workflows/ci.yml
  Makefile
  setup.py
Labels: needs force push, ready-to-merge

#2133 Unpin cloudpickle
  setup.py
Labels: backport-to-2020.06, ready-to-merge

#2089 Check observation shape conforms to observation_space
  src/garage/envs/gym_env.py
Labels: envs

#2140 Remove include_dashboard arg so that doctests pass
  docs/requirements.txt
  src/garage/sampler/ray_sampler.py
Labels: ready-to-merge

#2127 Make plotting plot the learner in BC
  src/garage/torch/algos/bc.py
Labels: ready-to-merge

#2123 Refactor REPS to use episode batch
  src/garage/tf/algos/reps.py
Labels: ready-to-merge

#2076 Add torch DQN
  benchmarks/src/garage_benchmarks/parameters.py
  examples/sim_policy.py
  examples/torch/dqn_atari.py
  examples/torch/dqn_cartpole.py
  examples/torch/watch_atari.py
  src/garage/_functions.py
  src/garage/envs/wrappers/fire_reset.py
  src/garage/envs/wrappers/max_and_skip.py
  src/garage/envs/wrappers/stack_frames.py
  src/garage/experiment/snapshotter.py
  src/garage/plotter/plotter.py
  src/garage/tf/plotter/plotter.py
  src/garage/torch/algos/__init__.py
  src/garage/torch/algos/dqn.py
  src/garage/torch/policies/discrete_qf_argmax_policy.py
  src/garage/torch/q_functions/discrete_cnn_q_function.py
  src/garage/trainer.py
  tests/garage/envs/wrappers/test_fire_reset.py
  tests/garage/envs/wrappers/test_stack_frames_env.py
  tests/garage/experiment/test_snapshotter.py
  tests/garage/torch/algos/test_dqn.py
  tests/garage/torch/policies/test_discrete_qf_argmax_policy.py
  tests/garage/torch/q_functions/test_discrete_cnn_q_function.py
  tests/integration_tests/test_examples.py
Labels: algos, ready-to-merge

#2137 Refactor te_npo to use episode batch
  src/garage/np/baselines/linear_multi_feature_baseline.py
  src/garage/tf/algos/te_npo.py
Labels: ready-to-merge

#2145 Fix flake of large test run under Travis
  Makefile
Labels: ready-to-merge

#2083 Check in GymEnv for env_info consistency
  src/garage/envs/gym_env.py
  tests/garage/envs/test_gym_env.py
Labels: envs, ready-to-merge

#2150 Add Torch TD3 and DQN to README
  README.md
Labels: ready-to-merge

#2141 Add docs for algos/CEM
  docs/index.md
  docs/user/algo_cem.md
  docs/user/algo_ppo.md
  docs/user/images/numpy.png
Labels: documentation, ready-to-merge

#2147 Add docs for logging and plotting
  docs/index.md
  docs/user/logging_plotting.md
  src/garage/__init__.py
Labels: ready-to-merge

#2138 Refactor RL2 to use EpisodeBatch
  examples/torch/maml_trpo_metaworld_ml1_push.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/rl2.py
  src/garage/tf/algos/te_npo.py
  src/garage/torch/algos/bc.py
Labels: ready-to-merge

#2067 Add docs for cluster setup
  docs/index.md
  docs/user/cluster_setup.md
Labels: ready-to-merge

#2156 Update LocalTFRunner to TFTrainer in garage script
  scripts/garage
Labels: ready-to-merge

#2153 Flatten input in primitives
  src/garage/tf/baselines/continuous_mlp_baseline.py
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/torch/policies/context_conditioned_policy.py
  src/garage/torch/policies/deterministic_mlp_policy.py
  src/garage/torch/policies/stochastic_policy.py
  tests/garage/tf/baselines/test_continuous_mlp_baseline.py
  tests/garage/tf/baselines/test_gaussian_cnn_baseline.py
  tests/garage/tf/baselines/test_gaussian_mlp_baseline.py
  tests/garage/torch/policies/test_deterministic_mlp_policy.py
  tests/garage/torch/policies/test_tanh_gaussian_mlp_policy.py
Labels: ready-to-merge

#2157 Blacklist KellyCoinflip from nightly build GymEnv tests
  tests/garage/tf/envs/test_gym_base.py
Labels: ready-to-merge

#2164 Organize algos and title case all pages
  docs/index.md
  docs/user/algo_bc.md
  docs/user/algo_cem.md
  docs/user/algo_ddpg.md
  docs/user/algo_erwr.md
  docs/user/algo_maml.md
  docs/user/algo_mtppo.md
  docs/user/algo_mtsac.md
  docs/user/algo_mttrpo.md
  docs/user/algo_ppo.md
  docs/user/algo_sac.md
  docs/user/algo_trpo.md
  docs/user/algo_vpg.md
  docs/user/cluster_setup.md
  docs/user/custom_worker.md
  docs/user/ensure_your_experiments_are_reproducible.md
  docs/user/logging_plotting.md
  docs/user/max_resource_usage.md
  docs/user/save_load_resume_exp.md
  docs/user/setting_up_your_development_environment.md
  docs/user/use_pretrained_network_to_start_new_experiment.md
Labels: documentation, ready-to-merge

#2082 Change env_infos from float to nparray
  src/garage/envs/mujoco/half_cheetah_dir_env.py
  src/garage/envs/mujoco/half_cheetah_vel_env.py
  tests/garage/envs/test_half_cheetah_meta_envs.py
Labels: envs, ready-to-merge
