Repository rlworkgroup/garage, pull requests merged in 2020-09, with the labels that each got.

#1980 Remove upper constraint for torchvision version
  setup.py
Labels: ready-to-merge

#1979 Deflake test_multiprocessing_sampler
  tests/garage/sampler/test_multiprocessing_sampler.py
Labels: backport-to-2020.06, ready-to-merge

#1985 Make gym dependency optional
  setup.py
  src/garage/_environment.py
  src/garage/np/exploration_policies/add_gaussian_noise.py
  src/garage/tf/plotter/plotter.py
  src/garage/torch/_functions.py
  tests/fixtures/envs/dummy/dummy_box_env.py
  tests/garage/test_environment.py
  tests/garage/torch/policies/test_categorical_cnn_policy.py
Labels: ready-to-merge

#1810 Move garage.misc.tensor_utils to garage.np
  .dockerignore
  docs/index.md
  docs/user/implement_algo.md
  docs/user/reuse_garage_policy.md
  examples/np/tutorial_cem.py
  examples/sim_policy.py
  examples/tf/tutorial_vpg.py
  examples/torch/tutorial_vpg.py
  src/garage/__init__.py
  src/garage/_dtypes.py
  src/garage/_functions.py
  src/garage/misc/__init__.py
  src/garage/misc/tensor_utils.py
  src/garage/np/__init__.py
  src/garage/np/_functions.py
  src/garage/plotter/plotter.py
  src/garage/sampler/utils.py
  src/garage/tf/_functions.py
  src/garage/tf/algos/_rl2npo.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/rl2.py
  src/garage/tf/algos/td3.py
  src/garage/tf/algos/te_npo.py
  src/garage/tf/models/module.py
  src/garage/tf/plotter/plotter.py
  src/garage/torch/algos/bc.py
  src/garage/torch/algos/ddpg.py
  src/garage/torch/algos/maml.py
  src/garage/torch/algos/mtsac.py
  src/garage/torch/algos/sac.py
  src/garage/torch/algos/vpg.py
  src/garage/torch/optimizers/conjugate_gradient_optimizer.py
  tests/garage/misc/__init__.py
  tests/garage/misc/test_tensor_utils.py
  tests/garage/np/test_functions.py
  tests/garage/sampler/test_utils.py
  tests/garage/test_functions.py
Labels: ready-to-merge

#1811 Move garage.tf.misc.tensor_utils to garage.tf
  src/garage/tf/__init__.py
  src/garage/tf/_functions.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/npo.py
  src/garage/tf/algos/reps.py
  src/garage/tf/algos/td3.py
  src/garage/tf/algos/te_npo.py
  src/garage/tf/baselines/continuous_mlp_baseline.py
  src/garage/tf/baselines/gaussian_cnn_baseline.py
  src/garage/tf/baselines/gaussian_mlp_baseline.py
  src/garage/tf/misc/__init__.py
  src/garage/tf/misc/tensor_utils.py
  src/garage/tf/optimizers/conjugate_gradient_optimizer.py
  src/garage/tf/optimizers/first_order_optimizer.py
  src/garage/tf/optimizers/lbfgs_optimizer.py
  src/garage/tf/optimizers/penalty_lbfgs_optimizer.py
  tests/garage/tf/misc/__init__.py
  tests/garage/tf/test_functions.py
Labels: ready-to-merge

#1996 Pin mujoco-py to fix gcc error
  setup.py
Labels: backport-to-2020.06, ready-to-merge

#1998 Narrow mujoco-py constraint
  setup.py
Labels: ready-to-merge

#2020 Remove unused garage.sampler.utils module
  src/garage/sampler/utils.py
  tests/garage/sampler/test_sampler.py
  tests/garage/sampler/test_utils.py
Labels: ready-to-merge

#2025 Fix wrong argument name in ppo benchmark
  benchmarks/src/garage_benchmarks/experiments/algos/ppo_garage_tf.py
Labels: ready-to-merge

#2026 Remove dependency on openai/baselines
  benchmarks/setup.py
  benchmarks/src/garage_benchmarks/benchmarks.py
  benchmarks/src/garage_benchmarks/parameters.py
Labels: ready-to-merge

#2027 Add docs for SAC
  docs/index.md
  docs/user/algo_sac.md
  docs/user/references.bib
Labels: ready-to-merge

#2000 Backport #1996 to release-2020.06
  setup.py
Labels: ready-to-merge

#2032 Add GH Actions CI badge to README
  README.md
Labels: ready-to-merge

#1953 Add docs for the concept experiment
  docs/index.md
  docs/user/concept_experiment.md
Labels: ready-to-merge

#2033 Compare other infos when testing env pickleable
  src/garage/envs/env_spec.py
  tests/garage/tf/envs/test_base.py
  tests/helpers.py
Labels: ready-to-merge

#2001 Fix CodeCov with GH Actions
  .github/workflows/ci.yml
Labels: ready-to-merge

#2034 Save git hash for auto benchmarking
  benchmarks/src/garage_benchmarks/helper.py
Labels: ready-to-merge

#2029 Backport #1975, #1908, and #1905; Fix #2028
  examples/torch/mtsac_metaworld_ml1_pick_place.py
  examples/torch/mtsac_metaworld_mt10.py
  examples/torch/mtsac_metaworld_mt50.py
  examples/torch/sac_half_cheetah_batch.py
  src/garage/envs/garage_env.py
  src/garage/torch/algos/mtsac.py
  src/garage/torch/algos/sac.py
  tests/garage/envs/test_garage_env.py
  tests/garage/torch/algos/test_mtsac.py
Labels: ready-to-merge

#2003 Improvements to SAC and MTSAC
  src/garage/torch/algos/mtsac.py
  src/garage/torch/algos/sac.py
Labels: ready-to-merge

#2036 Disable Ray Dashboard
  examples/tf/trpo_swimmer_ray_sampler.py
  examples/torch/trpo_pendulum_ray_sampler.py
  src/garage/sampler/ray_sampler.py
  tests/fixtures/sampler/ray_fixtures.py
Labels: ready-to-merge

#2022 Add torch DiscreteCNNModule & DiscreteCNNQFunction
  src/garage/torch/modules/__init__.py
  src/garage/torch/modules/cnn_module.py
  src/garage/torch/modules/discrete_cnn_module.py
  src/garage/torch/q_functions/__init__.py
  src/garage/torch/q_functions/discrete_cnn_q_function.py
  tests/garage/torch/modules/test_discrete_cnn_module.py
  tests/garage/torch/q_functions/test_discrete_cnn_q_function.py
Labels: ready-to-merge

#1997 Backport #1812 to 2020.06
  setup.py
  src/garage/sampler/utils.py
  src/garage/tf/policies/categorical_cnn_policy.py
  src/garage/tf/policies/categorical_gru_policy.py
  src/garage/tf/policies/categorical_lstm_policy.py
  src/garage/tf/policies/categorical_mlp_policy.py
  src/garage/tf/policies/continuous_mlp_policy.py
  src/garage/tf/policies/discrete_qf_derived_policy.py
  src/garage/tf/policies/gaussian_gru_policy.py
  src/garage/tf/policies/gaussian_lstm_policy.py
  src/garage/tf/policies/gaussian_mlp_policy.py
  src/garage/tf/policies/gaussian_mlp_task_embedding_policy.py
  src/garage/torch/policies/deterministic_mlp_policy.py
  src/garage/torch/policies/stochastic_policy.py
  tests/fixtures/envs/dummy/dummy_dict_env.py
  tests/fixtures/q_functions/simple_q_function.py
  tests/garage/replay_buffer/test_her_replay_buffer.py
  tests/garage/sampler/test_utils.py
  tests/garage/tf/policies/test_categorical_cnn_policy.py
  tests/garage/tf/policies/test_categorical_gru_policy.py
  tests/garage/tf/policies/test_categorical_lstm_policy.py
  tests/garage/tf/policies/test_categorical_mlp_policy.py
  tests/garage/tf/policies/test_continuous_mlp_policy.py
  tests/garage/tf/policies/test_gaussian_gru_policy.py
  tests/garage/tf/policies/test_gaussian_lstm_policy.py
  tests/garage/tf/policies/test_gaussian_mlp_policy.py
  tests/garage/tf/policies/test_gaussian_mlp_task_embedding_policy.py
  tests/garage/tf/policies/test_qf_derived_policy.py
  tests/garage/torch/policies/test_context_conditioned_policy.py
  tests/garage/torch/policies/test_deterministic_mlp_policy.py
  tests/garage/torch/policies/test_gaussian_mlp_policy.py
  tests/garage/torch/policies/test_tanh_gaussian_mlp_policy.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1993 Add torch DiscreteQFDerivedPolicy and DiscreteMLPQFunction
  docs/user/use_pretrained_network_to_start_new_experiment.md
  examples/tf/dqn_cartpole.py
  examples/tf/dqn_pong.py
  src/garage/tf/policies/__init__.py
  src/garage/tf/policies/discrete_qf_argmax_policy.py
  src/garage/torch/policies/__init__.py
  src/garage/torch/policies/discrete_qf_argmax_policy.py
  src/garage/torch/q_functions/__init__.py
  src/garage/torch/q_functions/discrete_mlp_q_function.py
  tests/garage/tf/algos/test_dqn.py
  tests/garage/tf/policies/test_discrete_qf_argmax_policy.py
  tests/garage/torch/policies/test_discrete_qf_argmax_policy.py
  tests/garage/torch/q_functions/test_discrete_mlp_q_function.py
Labels: ready-to-merge

#2023 Pickling the exploration policy
  benchmarks/src/garage_benchmarks/experiments/algos/td3_garage_tf.py
  examples/tf/td3_pendulum.py
  src/garage/np/exploration_policies/add_gaussian_noise.py
  src/garage/np/exploration_policies/epsilon_greedy_policy.py
  src/garage/np/exploration_policies/exploration_policy.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  src/garage/trainer.py
  tests/garage/np/exploration_strategies/__init__.py
  tests/garage/np/exploration_strategies/test_add_gaussian_noise.py
  tests/garage/np/exploration_strategies/test_epsilon_greedy_policy.py
  tests/garage/tf/algos/test_td3.py
Labels: backport-to-2019.10, backport-to-2020.06, ready-to-merge

#2039 Add PEARL doc
  docs/index.md
  docs/user/algo_pearl.md
  docs/user/references.bib
Labels: ready-to-merge

#2046 Update CHANGELOG for v2020.06.3
  CHANGELOG.md
Labels: ready-to-merge

#2037 Add RL2 doc
  docs/index.md
  docs/user/algo_rl2.md
Labels: ready-to-merge

#2056 Deflake test_update_envs_env_update
  tests/garage/sampler/test_multiprocessing_sampler.py
Labels: backport-to-2020.06, ready-to-merge

#2038 Add PPO doc
  docs/index.md
  docs/user/algo_ppo.md
  docs/user/references.bib
Labels: ready-to-merge

#2068 Pickling exploration policy (backport to release-2020.06)
  benchmarks/src/garage_benchmarks/experiments/algos/td3_garage_tf.py
  examples/tf/td3_pendulum.py
  src/garage/experiment/local_runner.py
  src/garage/np/exploration_policies/add_gaussian_noise.py
  src/garage/np/exploration_policies/epsilon_greedy_policy.py
  src/garage/np/exploration_policies/exploration_policy.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/tf/algos/td3.py
  src/garage/torch/algos/ddpg.py
  tests/garage/np/exploration_strategies/__init__.py
  tests/garage/np/exploration_strategies/test_add_gaussian_noise.py
  tests/garage/np/exploration_strategies/test_epsilon_greedy_policy.py
  tests/garage/tf/algos/test_td3.py
Labels: ready-to-merge

#2072 Disable snapshotting for auto benchmarks
  benchmarks/src/garage_benchmarks/benchmark_auto.py
  benchmarks/src/garage_benchmarks/helper.py
Labels: ready-to-merge

#2066 Mark test_multiprocessing_sampler flaky
  tests/garage/sampler/test_multiprocessing_sampler.py
Labels: ready-to-merge

#1883 Add get-started doc
  docs/index.md
  docs/user/algo_bc.md
  docs/user/get_started.md
Labels: ready-to-merge

#2073 Update MTSAC examples and MW version
  examples/torch/mtsac_metaworld_mt10.py
  examples/torch/mtsac_metaworld_mt50.py
  setup.py
Labels: ready-to-merge

#2045 Doc on Multi-Task PPO
  docs/index.md
  docs/user/algo_bc.md
  docs/user/algo_mtppo.md
  docs/user/references.bib
Labels: ready-to-merge

#2061 Add REINFORCE doc
  docs/index.md
  docs/user/algo_vpg.md
Labels: ready-to-merge

#2062 Add doctests to github actions
  .github/workflows/ci.yml
Labels: ready-to-merge

#2059 Add TRPO doc
  docs/index.md
  docs/user/algo_trpo.md
  docs/user/references.bib
Labels: ready-to-merge

#1893 Documentation on TD3
  .pylintrc
  docs/index.md
  docs/user/algo_bc.md
  docs/user/algo_td3.md
  docs/user/images/td3_tf_HalfCheetah-v2.png
  docs/user/images/td3_tf_Hopper-v2.png
  docs/user/images/td3_tf_InvertedDoublePendulum-v2.png
  docs/user/images/td3_tf_InvertedPendulum-v2.png
  docs/user/images/td3_tf_Swimmer-v2.png
  docs/user/images/tf.png
  docs/user/references.bib
Labels: ready-to-merge

#2042 Add environments concept documentation
  docs/index.md
  docs/user/environment.md
Labels: documentation, ready-to-merge
