Repository rlworkgroup/garage, pull requests merged in 2020-03, with the labels that each got.

#1186 Fix torch.TRPO unpickling
  src/garage/torch/optimizers/conjugate_gradient_optimizer.py
  tests/garage/torch/optimizers/test_torch_conjugate_gradient_optimizer.py
Labels: ready-to-merge

#1192 Add log_multitask_performance
  src/garage/__init__.py
  src/garage/_functions.py
  tests/garage/test_functions.py
Labels: ready-to-merge

#1190 Add RL2 Worker
  src/garage/sampler/__init__.py
  src/garage/sampler/rl2_sampler.py
  src/garage/tf/algos/rl2.py
  src/garage/tf/algos/rl2/__init__.py
  tests/garage/sampler/test_rl2_sampler.py
  tests/garage/sampler/test_rl2_worker.py
Labels: ready-to-merge

#1139 Rename self.evaluate for off-policy algos
  src/garage/np/algos/off_policy_rl_algorithm.py
  src/garage/tf/algos/ddpg.py
  src/garage/tf/algos/dqn.py
  src/garage/torch/algos/ddpg.py
Labels: ready-to-merge

#1194 Remove atari-py dep;Skip Defender envs in nightly tests
  setup.py
  tests/garage/tf/envs/test_base.py
Labels: ready-to-merge

#1196 Limit Docker memory usage
  Makefile
Labels: ready-to-merge

#1197 Fix torch compute_advantages
  src/garage/torch/algos/_utils.py
  tests/garage/torch/algos/test_torch_algo_utils.py
Labels: ready-to-merge

#1209 Fix torch compute_advantages
  src/garage/torch/algos/loss_function_utils.py
  tests/garage/torch/algos/test_loss_function_utils.py
Labels: ready-to-merge

#1217 Temporarily disable conda build
  Makefile
Labels: ready-to-merge

#1193 Fix flaky tests for ray sampler
  conftest.py
  examples/tf/trpo_swimmer_ray_sampler.py
  tests/garage/sampler/test_ray_batched_sampler.py
  tests/garage/tf/experiment/test_local_tf_runner.py
  tests/garage/tf/samplers/test_ray_batched_sampler_tf.py
Labels: ready-to-merge

#1228 Add RL2 to README
  README.md
Labels: ready-to-merge

#1227 MetaEval changes from paper
  src/garage/experiment/meta_evaluator.py
  src/garage/sampler/local_sampler.py
  tests/garage/experiment/test_meta_evaluator.py
Labels: ready-to-merge

#1184 Remove flaky marks on integration tests
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1178 Fix VecEnvExecutor + off-policy algorithms
  src/garage/sampler/off_policy_vectorized_sampler.py
  src/garage/sampler/on_policy_vectorized_sampler.py
  src/garage/sampler/vec_env_executor.py
  tests/garage/tf/algos/test_batch_polopt2.py
Labels: ready-to-merge

#1220 Skip mujoco dependent tests for external PRs
  .travis.yml
  Makefile
  docker/entrypoint-headless.sh
  docker/entrypoint-runtime.sh
  examples/tf/rl2_ppo_halfcheetah.py
  examples/tf/rl2_trpo_halfcheetah.py
  examples/torch/maml_ppo_half_cheetah_dir.py
  examples/torch/maml_trpo_half_cheetah_dir.py
  examples/torch/maml_vpg_half_cheetah_dir.py
  setup.cfg
  src/garage/envs/__init__.py
  src/garage/envs/mujoco/__init__.py
  src/garage/envs/mujoco/half_cheetah_dir_env.py
  src/garage/envs/mujoco/half_cheetah_env_meta_base.py
  src/garage/envs/mujoco/half_cheetah_vel_env.py
  tests/benchmarks/garage/tf/algos/test_benchmark_her.py
  tests/garage/envs/dm_control/test_dm_control_env.py
  tests/garage/envs/dm_control/test_dm_control_tf_policy.py
  tests/garage/envs/test_garage_env.py
  tests/garage/envs/test_half_cheetah_meta_envs.py
  tests/garage/experiment/test_task_sampler.py
  tests/garage/sampler/test_is_sampler.py
  tests/garage/sampler/test_off_policy_vectorized_sampler_integration.py
  tests/garage/tf/algos/test_ddpg.py
  tests/garage/tf/algos/test_npo.py
  tests/garage/tf/algos/test_ppo.py
  tests/garage/tf/algos/test_rl2ppo.py
  tests/garage/tf/algos/test_rl2trpo.py
  tests/garage/tf/algos/test_td3.py
  tests/garage/tf/algos/test_tnpg.py
  tests/garage/tf/algos/test_trpo.py
  tests/garage/torch/algos/test_ddpg.py
  tests/garage/torch/algos/test_maml_ppo.py
  tests/garage/torch/algos/test_maml_trpo.py
  tests/garage/torch/algos/test_maml_vpg.py
  tests/garage/torch/algos/test_pearl.py
  tests/garage/torch/algos/test_ppo.py
  tests/garage/torch/algos/test_sac.py
  tests/garage/torch/algos/test_trpo.py
  tests/garage/torch/algos/test_vpg.py
  tests/integration_tests/test_examples.py
Labels: needs force push

#1250 Use a GH token in the CI to retrieve packages
  .travis.yml
  Makefile
  setup.py
Labels: ready-to-merge

#1120 Update setup_macos.sh to include macOS 10.15.2
  scripts/setup_macos.sh
Labels: ready-to-merge

#1242 Add SAC to README
  README.md
Labels: ready-to-merge

#1248 Fix default X axis under wrap_experiment
  src/garage/experiment/experiment.py
Labels: ready-to-merge

#1252 Use a GH token in the CI to retrieve packages (#1250)
  Makefile
  setup.py
Labels: ready-to-merge

#1188 Add minibatch and optimize_epoch for VPG(PyTorch) and PPO(PyTorch)
  src/garage/tf/algos/ppo.py
  src/garage/torch/algos/maml.py
  src/garage/torch/algos/ppo.py
  src/garage/torch/algos/trpo.py
  src/garage/torch/algos/vpg.py
  src/garage/torch/modules/gaussian_mlp_module.py
  tests/benchmarks/garage/tf/algos/test_benchmark_ppo.py
Labels: ready-to-merge

#1256 Restrict test discovery to tests directory
  setup.cfg
Labels: ready-to-merge

#1258 Fix experiment 'name' scope
  src/garage/experiment/experiment.py
Labels: ready-to-merge

#1254 Unpin torch+torchvision
  setup.py
Labels: ready-to-merge

#1247 Install dm_control from PyPI
  setup.py
  src/garage/envs/dm_control/dm_control_env.py
Labels: needs force push, ready-to-merge

#1257 Remove MuJoCo key for normal and large test jobs
  Makefile
  setup.cfg
  tests/garage/envs/test_half_cheetah_meta_envs.py
  tests/garage/experiment/test_task_sampler.py
  tests/garage/tf/algos/test_ddpg.py
  tests/garage/tf/algos/test_npo.py
  tests/garage/tf/algos/test_ppo.py
  tests/garage/tf/algos/test_rl2ppo.py
  tests/garage/tf/algos/test_rl2trpo.py
  tests/garage/tf/algos/test_tnpg.py
  tests/garage/tf/algos/test_trpo.py
  tests/garage/torch/algos/test_ddpg.py
  tests/garage/torch/algos/test_maml.py
  tests/garage/torch/algos/test_maml_ppo.py
  tests/garage/torch/algos/test_maml_trpo.py
  tests/garage/torch/algos/test_maml_vpg.py
  tests/garage/torch/algos/test_pearl.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1241 Add more PEARL examples
  examples/torch/pearl_half_cheetah_vel.py
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1253 Fix duplicate window rendering for Plotter
  src/garage/experiment/local_runner.py
  src/garage/tf/plotter/plotter.py
Labels: needs force push

#1262 Fix typo which broke CI
  tests/integration_tests/test_examples.py
Labels: ready-to-merge

#1249 Wrap exp name parameters
  src/garage/experiment/experiment.py
  tests/garage/experiment/test_experiment.py
Labels: ready-to-merge
